In [157]:
import numpy as np
import pandas as pd

## Exploratory Data Analysis

In [158]:
data = pd.read_csv("book ratings dataset/Books Data with Category Language and Summary/Preprocessed_data.csv")

In [159]:
data

,Unnamed: 0,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
0,0,2,"stockton, california, usa",18.0000,0195153448,0,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,Provides an introduction to classical myths pl...,en,['Social Science'],stockton,california,usa
1,1,8,"timmins, ontario, canada",34.7439,0002005018,5,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],timmins,ontario,canada
2,2,11400,"ottawa, ontario, canada",49.0000,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,ontario,canada
3,3,11676,"n/a, n/a, n/a",34.7439,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],NaN,NaN,NaN
4,4,41385,"sudbury, ontario, canada",34.7439,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],sudbury,ontario,canada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031170,1031170,278851,"dallas, texas, usa",33.0000,0743203763,0,As Hogan Said . . . : The 389 Best Things Anyo...,Randy Voorhees,2000.0,Simon & Schuster,http://images.amazon.com/images/P/0743203763.0...,http://images.amazon.com/images/P/0743203763.0...,http://images.amazon.com/images/P/0743203763.0...,Golf lovers will revel in this collection of t...,en,['Humor'],dallas,texas,usa
1031171,1031171,278851,"dallas, texas, usa",33.0000,0767907566,5,All Elevations Unknown: An Adventure in the He...,Sam Lightner,2001.0,Broadway Books,http://images.amazon.com/images/P/0767907566.0...,http://images.amazon.com/images/P/0767907566.0...,http://images.amazon.com/images/P/0767907566.0...,A daring twist on the travel-adventure genre t...,en,['Nature'],dallas,texas,usa
1031172,1031172,278851,"dallas, texas, usa",33.0000,0884159221,7,Why stop?: A guide to Texas historical roadsid...,Claude Dooley,1985.0,Lone Star Books,http://images.amazon.com/images/P/0884159221.0...,http://images.amazon.com/images/P/0884159221.0...,http://images.amazon.com/images/P/0884159221.0...,9,9,9,dallas,texas,usa
1031173,1031173,278851,"dallas, texas, usa",33.0000,0912333022,7,The Are You Being Served? Stories: 'Camping In...,Jeremy Lloyd,1997.0,Kqed Books,http://images.amazon.com/images/P/0912333022.0...,http://images.amazon.com/images/P/0912333022.0...,http://images.amazon.com/images/P/0912333022.0...,These hilarious stories by the creator of publ...,en,['Fiction'],dallas,texas,usa
1031174,1031174,278851,"dallas, texas, usa",33.0000,1569661057,10,"Dallas Street Map Guide and Directory, 2000 Ed...",Mapsco,1999.0,American Map Corporation,http://images.amazon.com/images/P/1569661057.0...,http://images.amazon.com/images/P/1569661057.0...,http://images.amazon.com/images/P/1569661057.0...,9,9,9,dallas,texas,usa

In [160]:
data.drop(columns=["Unnamed: 0"], inplace=True)
data.head()

,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
0,2,"stockton, california, usa",18.0000,0195153448,0,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,Provides an introduction to classical myths pl...,en,['Social Science'],stockton,california,usa
1,8,"timmins, ontario, canada",34.7439,0002005018,5,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],timmins,ontario,canada
2,11400,"ottawa, ontario, canada",49.0000,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,ontario,canada
3,11676,"n/a, n/a, n/a",34.7439,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],NaN,NaN,NaN
4,41385,"sudbury, ontario, canada",34.7439,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],sudbury,ontario,canada

In [161]:
data.shape

(1031175, 18)

In [162]:
data  = data[data['rating'] != 0]

In [163]:
data.shape

(383852, 18)

In [166]:
data.groupby("book_title").count()["rating"].reset_index().sort_values(by="rating", ascending=False)

                                               book_title  rating
110234                          The Lovely Bones: A Novel     707
132246                                        Wild Animus     581
102707                                  The Da Vinci Code     494
116201                            The Secret Life of Bees     406
111955                         The Nanny Diaries: A Novel     393
...                                                   ...     ...
54565                             Journeys to Door County       1
54563   Journeys of Simplicity: Traveling Light With T...       1
54562                            Journeys into Past Lives       1
54561   Journeys down the line: Building the Trans-Ala...       1
135572                                  Ã?Â?thique en toc       1

[135573 rows x 2 columns]

In [167]:
data.groupby("user_id").count()["rating"].reset_index().sort_values(by="rating", ascending=False)

       user_id  rating
2719     11676    6943
24101    98391    5691
46279   189835    1899
37648   153662    1845
5615     23902    1180
...        ...     ...
33246   135660       1
33250   135677       1
33252   135684       1
6297     26542       1
34046   138846       1

[68092 rows x 2 columns]

In [168]:
# data.pivot_table(index="book_title", columns="user_id", values="rating")

### Pandas currently does not support such big matrices. Need to reduce the dataset

In [169]:
x = data.groupby("user_id").count()["rating"] > 30
significant_users = x[x].index
significant_users

Int64Index([   254,    507,    638,    643,    882,   1211,   1424,   1435,
              1733,   1848,
            ...
            277203, 277427, 277478, 278026, 278137, 278188, 278356, 278418,
            278582, 278633],
           dtype='int64', name='user_id', length=2067)

In [170]:
data_modified = data[data["user_id"].isin(significant_users)]
data_modified

,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
3,11676,"n/a, n/a, n/a",34.7439,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],NaN,NaN,NaN
8,116866,"ottawa, ,",34.7439,0002005018,9,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,",",NaN
13,219008,"halifax, nova scotia, canada",60.0000,0002005018,7,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],halifax,nova scotia,canada
14,263325,"fredericton, new brunswick, canada",27.0000,0002005018,6,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],fredericton,new brunswick,canada
19,35704,"kansas city, missouri, usa",53.0000,0374157065,6,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,"Describes the great flu epidemic of 1918, an o...",en,['Medical'],kansas city,missouri,usa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031015,278418,"omaha, nebraska, usa",34.7439,155882068X,5,The Balloon Man (Crime Classics),Charlotte Armstrong,1990.0,Independent Pub Group,http://images.amazon.com/images/P/155882068X.0...,http://images.amazon.com/images/P/155882068X.0...,http://images.amazon.com/images/P/155882068X.0...,9,9,9,omaha,nebraska,usa
1031048,278418,"omaha, nebraska, usa",34.7439,1569751544,3,The Sleep Solution: A 21-Night Program to Bett...,Nigel Ball,1998.0,Ulysses Press,http://images.amazon.com/images/P/1569751544.0...,http://images.amazon.com/images/P/1569751544.0...,http://images.amazon.com/images/P/1569751544.0...,Discusses sleep disturbances and normal sleep ...,en,['Health & Fitness'],omaha,nebraska,usa
1031137,278633,"sandy, utah, usa",34.7439,0393045900,9,Inner Hunger: A Young Woman's Struggle Through...,Marianne Apostolides,1998.0,W. W. Norton & Company,http://images.amazon.com/images/P/0393045900.0...,http://images.amazon.com/images/P/0393045900.0...,http://images.amazon.com/images/P/0393045900.0...,"The author provides a dramatic, detailed accou...",en,['Self-Help'],sandy,utah,usa
1031141,278633,"sandy, utah, usa",34.7439,1562477544,7,A Song for Jeffrey (Ag Fiction (American Girl)),Constance M. Foland,1999.0,Pleasant Company Publications,http://images.amazon.com/images/P/1562477544.0...,http://images.amazon.com/images/P/1562477544.0...,http://images.amazon.com/images/P/1562477544.0...,9,9,9,sandy,utah,usa
1031142,278633,"sandy, utah, usa",34.7439,1896095186,5,Pool-Hopping,Anne Fleming,2000.0,Polestar Book Publishers,http://images.amazon.com/images/P/1896095186.0...,http://images.amazon.com/images/P/1896095186.0...,http://images.amazon.com/images/P/1896095186.0...,The fascinating characters in this short story...,en,['Fiction'],sandy,utah,usa

In [171]:
data_modified.groupby("book_title").count()["rating"].reset_index().sort_values(by="rating", ascending=False)

                                              book_title  rating
73363                          The Lovely Bones: A Novel     195
29870   Harry Potter and the Chamber of Secrets (Book 2)     160
68049                                  The Da Vinci Code     154
10738                              Bridget Jones's Diary     142
29887  Harry Potter and the Prisoner of Azkaban (Book 3)     140
...                                                  ...     ...
35227                  Jacob's Rescue: A Holocaust Story       1
35226  Jacob's Ladder: A Story of Virginia During the...       1
35225                                      Jacob's Hands       1
35224                                       Jacob's Gift       1
90544                                  Ã?Â?thique en toc       1

[90545 rows x 2 columns]

In [172]:
y = data_modified.groupby("book_title").count()["rating"] >=70
significant_books = y[y].index
significant_books

Index(['1st to Die: A Novel', 'A Painted House', 'A Time to Kill',
       'Angels & Demons', 'Bridget Jones's Diary',
       'Divine Secrets of the Ya-Ya Sisterhood: A Novel', 'Dreamcatcher',
       'Fahrenheit 451', 'Girl with a Pearl Earring', 'Good in Bed',
       'Hannibal', 'Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Order of the Phoenix (Book 5)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)',
       'Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))',
       'House of Sand and Fog', 'Interview with the Vampire', 'Jurassic Park',
       'Life of Pi', 'Me Talk Pretty One Day', 'Misery', 'Red Dragon',
       'She's Come Undone (Oprah's Book Club (Paperback))',
       'Snow Falling on Cedars', 'Summer Sisters', 'The Catcher in the Rye',
       'The Chamber', 'The Client', 'The Da Vinci Code',
       'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
       'The Firm', 'The Five People You Meet in Heaven',
       'The Girls' Guide to Hunting and Fishing', 'The Joy Luck Club',
       'The Lovely Bones: A Novel', 'The Nanny Diaries: A Novel',
       'The Notebook', 'The Partner', 'The Pelican Brief',
       'The Pilot's Wife : A Novel', 'The Rainmaker',
       'The Red Tent (Bestselling Backlist)', 'The Runaway Jury',
       'The Secret Life of Bees', 'The Street Lawyer', 'The Testament',
       'The Two Towers (The Lord of the Rings, Part 2)',
       'The Vampire Lestat (Vampire Chronicles, Book II)', 'Timeline',
       'To Kill a Mockingbird',
       'Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson',
       'Where the Heart Is (Oprah's Book Club (Paperback))', 'Wild Animus'],
      dtype='object', name='book_title')

In [173]:
data_modified = data_modified[data_modified["book_title"].isin(significant_books)]
data_modified

,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
106,7346,"sunnyvale, california, usa",49.0000,0440234743,9,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],sunnyvale,california,usa
111,11224,"tumwater, washington, usa",51.0000,0440234743,6,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],tumwater,washington,usa
112,11676,"n/a, n/a, n/a",34.7439,0440234743,9,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],NaN,NaN,NaN
115,13552,"cordova, tennessee, usa",32.0000,0440234743,8,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],cordova,tennessee,usa
128,23511,"chapel hill, north carolina, usa",56.0000,0440234743,8,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],chapel hill,north carolina,usa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995018,222035,"bristol, connecticut, usa",56.0000,0553455486,7,The Runaway Jury,JOHN GRISHAM,1996.0,Random House Audio,http://images.amazon.com/images/P/0553455486.0...,http://images.amazon.com/images/P/0553455486.0...,http://images.amazon.com/images/P/0553455486.0...,9,9,9,bristol,connecticut,usa
997749,225763,"san francisco, california, usa",34.7439,0553526774,5,Hannibal,Thomas Harris,1999.0,Random House Audio Publishing Group,http://images.amazon.com/images/P/0553526774.0...,http://images.amazon.com/images/P/0553526774.0...,http://images.amazon.com/images/P/0553526774.0...,9,9,9,san francisco,california,usa
1021726,259901,"thompson, manitoba, canada",34.7439,0395647398,10,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,1992.0,Houghton Mifflin,http://images.amazon.com/images/P/0395647398.0...,http://images.amazon.com/images/P/0395647398.0...,http://images.amazon.com/images/P/0395647398.0...,9,9,9,thompson,manitoba,canada
1025107,266865,"reston, virginia, usa",33.0000,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973.0,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,9,9,9,reston,virginia,usa
1029323,275970,"pittsburgh, pennsylvania, usa",46.0000,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001.0,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,9,9,9,pittsburgh,pennsylvania,usa

## Matrix of books against users

In [174]:
matrix = data_modified.pivot_table(index="user_id", columns="book_title", values="rating")
matrix

book_title,1st to Die: A Novel,A Painted House,A Time to Kill,Angels & Demons,Bridget Jones's Diary,Divine Secrets of the Ya-Ya Sisterhood: A Novel,Dreamcatcher,Fahrenheit 451,Girl with a Pearl Earring,Good in Bed,...,The Secret Life of Bees,The Street Lawyer,The Testament,"The Two Towers (The Lord of the Rings, Part 2)","The Vampire Lestat (Vampire Chronicles, Book II)",Timeline,To Kill a Mockingbird,"Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",Where the Heart Is (Oprah's Book Club (Paperback)),Wild Animus
user_id,,,,,,,,,,,,,,,,,,,,,
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN
882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278633,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [175]:
def subtract_row_mean(row):
    row_mean = np.nanmean(row)  # Calculate the mean excluding NaN values
    return row.apply(lambda x: x - row_mean if not np.isnan(x) else x)

# Apply the function to each row of the DataFrame
matrix_normalized = matrix.apply(subtract_row_mean, axis=1)



# Display the resulting DataFrame
matrix_normalized

book_title,1st to Die: A Novel,A Painted House,A Time to Kill,Angels & Demons,Bridget Jones's Diary,Divine Secrets of the Ya-Ya Sisterhood: A Novel,Dreamcatcher,Fahrenheit 451,Girl with a Pearl Earring,Good in Bed,...,The Secret Life of Bees,The Street Lawyer,The Testament,"The Two Towers (The Lord of the Rings, Part 2)","The Vampire Lestat (Vampire Chronicles, Book II)",Timeline,To Kill a Mockingbird,"Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",Where the Heart Is (Oprah's Book Club (Paperback)),Wild Animus
user_id,,,,,,,,,,,,,,,,,,,,,
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,NaN,NaN,-0.857143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.142857,NaN,NaN,NaN,NaN,NaN,NaN
882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278633,NaN,NaN,NaN,NaN,-4.666667,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [176]:
matrix_normalized.fillna(0, inplace=True)

In [177]:
matrix_normalized

book_title,1st to Die: A Novel,A Painted House,A Time to Kill,Angels & Demons,Bridget Jones's Diary,Divine Secrets of the Ya-Ya Sisterhood: A Novel,Dreamcatcher,Fahrenheit 451,Girl with a Pearl Earring,Good in Bed,...,The Secret Life of Bees,The Street Lawyer,The Testament,"The Two Towers (The Lord of the Rings, Part 2)","The Vampire Lestat (Vampire Chronicles, Book II)",Timeline,To Kill a Mockingbird,"Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",Where the Heart Is (Oprah's Book Club (Paperback)),Wild Animus
user_id,,,,,,,,,,,,,,,,,,,,,
254,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.166667,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
507,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
638,0.0,0.0,-0.857143,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0
882,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1211,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277427,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
278137,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
278188,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
278356,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
278633,0.0,0.0,0.000000,0.0,-4.666667,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

# Making user clusters based on user-user collaborative filtering using common book ratings

In [178]:
from sklearn.metrics.pairwise import cosine_similarity

In [179]:
user_similarity = cosine_similarity(matrix_normalized)

In [180]:
user_similarity

array([[ 1.        ,  0.        ,  0.        , ...,  0.        ,
        -0.05270463,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  0.06299408],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.05270463,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.06299408, ...,  0.        ,
         0.        ,  1.        ]])

In [181]:
user_similarity.shape

(1488, 1488)

In [1]:
def get_similar_users(user_id):
    index = np.where(matrix.index==user_id)[0][0]
    neareset_neighbours = sorted(list(enumerate(user_similarity[index])), key=lambda x:x[1], reverse=True)[1:]
    return neareset_neighbours

In [183]:
similar_user_indices_with_similarity = get_similar_users(254)
similar_user_indices = [x[0] for x in similar_user_indices_with_similarity]
similar_user_indices_with_similarity

[(657, 0.9666666666666668),
 (247, 0.7745966692414833),
 (971, 0.7453559924999297),
 (1133, 0.7219061292050056),
 (615, 0.7075942729929445),
 (878, 0.6499999999999999),
 (947, 0.5530100413375025),
 (459, 0.516483155667427),
 (1149, 0.41912746045427834),
 (1006, 0.3012320380383545),
 (743, 0.29999999999999977),
 (1286, 0.2808008596977891),
 (1084, 0.2635231383473651),
 (27, 0.18203641092364062),
 (1403, 0.1792842914001585),
 (374, 0.17808764796017387),
 (551, 0.175682092231576),
 (561, 0.17320508075688712),
 (865, 0.17320508075688684),
 (1477, 0.1721325931647735),
 (1178, 0.15811388300841842),
 (690, 0.15313266275716822),
 (1228, 0.14978386515820258),
 (685, 0.1490711984999855),
 (845, 0.1490711984999855),
 (828, 0.14907119849998546),
 (211, 0.14907119849998532),
 (239, 0.14907119849998532),
 (877, 0.14808721943977257),
 (97, 0.1465988679020929),
 (112, 0.1465988679020929),
 (316, 0.1465988679020929),
 (286, 0.14638501094227946),
 (674, 0.14638501094227946),
 (189, 0.14288690166235157),
 (531, 0.14228026515269482),
 (1303, 0.1408590424547523),
 (725, 0.1408590424547522),
 (62, 0.13601571112444077),
 (1261, 0.13483997249264792),
 (902, 0.13333333333333294),
 (9, 0.13333333333333275),
 (1040, 0.13333333333333242),
 (48, 0.1290994448735801),
 (370, 0.1290994448735801),
 (1382, 0.1290994448735801),
 (131, 0.12909944487358008),
 (334, 0.12909944487358008),
 (378, 0.12909944487358008),
 (471, 0.12909944487358008),
 (619, 0.12909944487358008),
 (663, 0.12909944487358008),
 (723, 0.12909944487358008),
 (804, 0.12909944487358008),
 (806, 0.12909944487358008),
 (876, 0.12909944487358008),
 (1073, 0.12909944487358008),
 (1089, 0.12909944487358008),
 (1127, 0.12909944487358008),
 (1169, 0.12909944487358008),
 (1235, 0.12909944487358008),
 (1236, 0.12909944487358008),
 (1464, 0.12909944487358008),
 (977, 0.12741179785940607),
 (1115, 0.1274117978594058),
 (889, 0.12678304352149355),
 (1163, 0.12659242088545788),
 (39, 0.12602520756252047),
 (187, 0.12449063686859087),
 (73, 0.12247448713915858),
 (1044, 0.12247448713915847),
 (1117, 0.12247448713915804),
 (402, 0.118733922536494),
 (476, 0.11677484162422803),
 (1423, 0.11677484162422803),
 (1231, 0.11547005383792473),
 (1197, 0.11268723396380186),
 (666, 0.11268723396380179),
 (897, 0.11268723396380179),
 (1051, 0.11141720290623071),
 (939, 0.10706067580626177),
 (645, 0.10540925533894561),
 (1033, 0.10540925533894561),
 (49, 0.1054092553389456),
 (642, 0.1054092553389456),
 (1182, 0.1054092553389456),
 (1150, 0.10499989746108739),
 (591, 0.10336227882434004),
 (802, 0.10287674029332246),
 (1091, 0.09999999999999984),
 (1268, 0.09999999999999981),
 (546, 0.09999999999999964),
 (1333, 0.09583148474999063),
 (1456, 0.0946762136662298),
 (53, 0.09271726499455286),
 (841, 0.09185586535436889),
 (581, 0.09160572248286848),
 (103, 0.09128709291752736),
 (565, 0.09128709291752736),
 (582, 0.09128709291752736),
 (1107, 0.09058216273156733),
 (975, 0.0898933149950986),
 (509, 0.08947924869885956),
 (358, 0.08784585919193286),
 (98, 0.08784104611578798),
 (64, 0.08728715609439686),
 (275, 0.08257228238447675),
 (501, 0.08257228238447675),
 (859, 0.08257228238447675),
 (910, 0.08115430675802916),
 (1305, 0.08017837257372706),
 (438, 0.07809984034708783),
 (1326, 0.07698003589195),
 (936, 0.07497072027996915),
 (29, 0.07453559924999285),
 (174, 0.07453559924999285),
 (288, 0.07453559924999285),
 (608, 0.07453559924999285),
 (739, 0.07453559924999285),
 (792, 0.07453559924999276),
 (989, 0.07453559924999273),
 (1300, 0.07453559924999273),
 (1429, 0.07453559924999273),
 (215, 0.07453559924999272),
 (243, 0.07453559924999272),
 (573, 0.07453559924999272),
 (801, 0.07453559924999266),
 (1222, 0.07453559924999266),
 (44, 0.07453559924999245),
 (461, 0.07423074889580875),
 (1376, 0.07284927963857715),
 (1331, 0.07042952122737606),
 (382, 0.06960575579871282),
 (1275, 0.06710835095665944),
 (1159, 0.06693740422746919),
 (1446, 0.06666666666666647),
 (43, 0.06666666666666636),
 (1287, 0.06666666666666621),
 (1156, 0.06642111641550691),
 (238, 0.06620484352491288),
 (517, 0.06546536707079725),
 (1023, 0.06454972243679002),
 (986, 0.06367145399670111),
 (13, 0.06123724356957919),
 (297, 0.059761430466719515),
 (895, 0.05895063447465605),
 (57, 0.0586924985299381),
 (205, 0.05634361698190087),
 (191, 0.05634361698190071),
 (1444, 0.05622804020997689),
 (372, 0.05530530403299715),
 (283, 0.05449820181420496),
 (1404, 0.05413319619607646),
 (36, 0.05355947466554004),
 (846, 0.05270462766947289),
 (170, 0.05270462766947281),
 (298, 0.05270462766947281),
 (300, 0.05270462766947281),
 (451, 0.05270462766947281),
 (1258, 0.05270462766947281),
 (1334, 0.05270462766947281),
 (380, 0.0527046276694728),
 (1454, 0.052704627669472745),
 (1079, 0.05258304820496173),
 (158, 0.05110033598581353),
 (148, 0.049082035556361446),
 (1058, 0.048795003647426484),
 (335, 0.04803844614152606),
 (557, 0.048003499554275256),
 (1391, 0.046918930698474845),
 (387, 0.046373889576016666),
 (79, 0.04569003742049371),
 (656, 0.04442616583193177),
 (731, 0.04318335170875287),
 (887, 0.04200840252084012),
 (1220, 0.0408248290463862),
 (110, 0.040824829046386193),
 (583, 0.04082482904638615),
 (1243, 0.04082482904638601),
 (1411, 0.04082482904638601),
 (1237, 0.03796631983009986),
 (347, 0.037760998839451526),
 (201, 0.03650023998986676),
 (202, 0.03577767177001834),
 (1452, 0.0352297424312617),
 (773, 0.033333333333333215),
 (1193, 0.0333333333333332),
 (1241, 0.03227486121839502),
 (1096, 0.028171808490950356),
 (52, 0.027524094128158916),
 (31, 0.02707651805369401),
 (550, 0.024397501823713242),
 (1135, 0.021821789023599082),
 (375, 0.020942695414584697),
 (1365, 0.02036571006878276),
 (1368, 0.01807753815155455),
 (978, 0.0063448915635567595),
 (715, 0.004364357804719815),
 (185, 0.0036739636693448956),
 (843, 1.376084797788694e-17),
 (873, 4.359180029617919e-19),
 (1, 0.0),
 (2, 0.0),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0),
 (6, 0.0),
 (7, 0.0),
 (8, 0.0),
 (10, 0.0),
 (11, 0.0),
 (12, 0.0),
 (14, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.0),
 (20, 0.0),
 (21, 0.0),
 (22, 0.0),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (28, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (37, 0.0),
 (38, 0.0),
 (40, 0.0),
 (45, 0.0),
 (46, 0.0),
 (47, 0.0),
 (50, 0.0),
 (51, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (58, 0.0),
 (59, 0.0),
 (60, 0.0),
 (61, 0.0),
 (63, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.0),
 (68, 0.0),
 (69, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (74, 0.0),
 (75, 0.0),
 (76, 0.0),
 (77, 0.0),
 (80, 0.0),
 (81, 0.0),
 (83, 0.0),
 (84, 0.0),
 (85, 0.0),
 (86, 0.0),
 (87, 0.0),
 (88, 0.0),
 (89, 0.0),
 (90, 0.0),
 (91, 0.0),
 (92, 0.0),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (96, 0.0),
 (99, 0.0),
 (100, 0.0),
 (101, 0.0),
 (102, 0.0),
 (104, 0.0),
 (105, 0.0),
 (106, 0.0),
 (107, 0.0),
 (111, 0.0),
 (113, 0.0),
 (115, 0.0),
 (116, 0.0),
 (117, 0.0),
 (118, 0.0),
 (119, 0.0),
 (120, 0.0),
 (121, 0.0),
 (122, 0.0),
 (124, 0.0),
 (125, 0.0),
 (126, 0.0),
 (127, 0.0),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (132, 0.0),
 (133, 0.0),
 (134, 0.0),
 (135, 0.0),
 (136, 0.0),
 (137, 0.0),
 (138, 0.0),
 (139, 0.0),
 (140, 0.0),
 (141, 0.0),
 (142, 0.0),
 (143, 0.0),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (149, 0.0),
 (150, 0.0),
 (151, 0.0),
 (152, 0.0),
 (153, 0.0),
 (154, 0.0),
 (155, 0.0),
 (156, 0.0),
 (159, 0.0),
 (160, 0.0),
 (161, 0.0),
 (162, 0.0),
 (163, 0.0),
 (164, 0.0),
 (166, 0.0),
 (167, 0.0),
 (168, 0.0),
 (169, 0.0),
 (171, 0.0),
 (172, 0.0),
 (173, 0.0),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0),
 (182, 0.0),
 (183, 0.0),
 (184, 0.0),
 (186, 0.0),
 (188, 0.0),
 (190, 0.0),
 (192, 0.0),
 (193, 0.0),
 (194, 0.0),
 (196, 0.0),
 (197, 0.0),
 (198, 0.0),
 (199, 0.0),
 (200, 0.0),
 (203, 0.0),
 (204, 0.0),
 (206, 0.0),
 (207, 0.0),
 (208, 0.0),
 (209, 0.0),
 (212, 0.0),
 (213, 0.0),
 (214, 0.0),
 (216, 0.0),
 (217, 0.0),
 (218, 0.0),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0),
 (222, 0.0),
 (223, 0.0),
 (224, 0.0),
 (225, 0.0),
 (226, 0.0),
 (227, 0.0),
 (228, 0.0),
 (229, 0.0),
 (230, 0.0),
 (231, 0.0),
 (232, 0.0),
 (234, 0.0),
 (235, 0.0),
 (236, 0.0),
 (237, 0.0),
 (240, 0.0),
 (241, 0.0),
 (242, 0.0),
 (244, 0.0),
 (245, 0.0),
 (246, 0.0),
 (248, 0.0),
 (249, 0.0),
 (250, 0.0),
 (251, 0.0),
 (253, 0.0),
 (254, 0.0),
 (255, 0.0),
 (256, 0.0),
 (257, 0.0),
 (258, 0.0),
 (259, 0.0),
 (260, 0.0),
 (261, 0.0),
 (262, 0.0),
 (263, 0.0),
 (265, 0.0),
 (266, 0.0),
 (267, 0.0),
 (269, 0.0),
 (270, 0.0),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.0),
 (276, 0.0),
 (277, 0.0),
 (278, 0.0),
 (279, 0.0),
 (280, 0.0),
 (281, 0.0),
 (282, 0.0),
 (284, 0.0),
 (285, 0.0),
 (287, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.0),
 (295, 0.0),
 (296, 0.0),
 (299, 0.0),
 (302, 0.0),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0),
 (307, 0.0),
 (308, 0.0),
 (309, 0.0),
 (310, 0.0),
 (311, 0.0),
 (313, 0.0),
 (314, 0.0),
 (315, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0),
 (320, 0.0),
 (322, 0.0),
 (323, 0.0),
 (324, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (329, 0.0),
 (330, 0.0),
 (331, 0.0),
 (332, 0.0),
 (333, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (342, 0.0),
 (343, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (348, 0.0),
 (349, 0.0),
 (350, 0.0),
 (351, 0.0),
 (353, 0.0),
 (354, 0.0),
 (355, 0.0),
 (356, 0.0),
 (357, 0.0),
 (359, 0.0),
 (360, 0.0),
 (361, 0.0),
 (362, 0.0),
 (363, 0.0),
 (364, 0.0),
 (365, 0.0),
 (366, 0.0),
 (367, 0.0),
 (368, 0.0),
 (369, 0.0),
 (371, 0.0),
 (373, 0.0),
 (376, 0.0),
 (379, 0.0),
 (381, 0.0),
 (384, 0.0),
 (385, 0.0),
 (386, 0.0),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.0),
 (392, 0.0),
 (393, 0.0),
 (394, 0.0),
 (395, 0.0),
 (396, 0.0),
 (397, 0.0),
 (398, 0.0),
 (399, 0.0),
 (400, 0.0),
 (401, 0.0),
 (403, 0.0),
 (404, 0.0),
 (406, 0.0),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0),
 (410, 0.0),
 (411, 0.0),
 (412, 0.0),
 (413, 0.0),
 (416, 0.0),
 (417, 0.0),
 (418, 0.0),
 (420, 0.0),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (429, 0.0),
 (430, 0.0),
 (431, 0.0),
 (432, 0.0),
 (433, 0.0),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (439, 0.0),
 (441, 0.0),
 (442, 0.0),
 (443, 0.0),
 (444, 0.0),
 (445, 0.0),
 (446, 0.0),
 (448, 0.0),
 (449, 0.0),
 (452, 0.0),
 (453, 0.0),
 (454, 0.0),
 (455, 0.0),
 (456, 0.0),
 (458, 0.0),
 (460, 0.0),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (466, 0.0),
 (467, 0.0),
 (469, 0.0),
 (470, 0.0),
 (472, 0.0),
 (473, 0.0),
 (474, 0.0),
 (475, 0.0),
 (477, 0.0),
 (478, 0.0),
 (479, 0.0),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (483, 0.0),
 (484, 0.0),
 (485, 0.0),
 (486, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.0),
 (490, 0.0),
 (491, 0.0),
 (492, 0.0),
 (493, 0.0),
 (494, 0.0),
 (495, 0.0),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.0),
 (503, 0.0),
 (504, 0.0),
 (505, 0.0),
 (506, 0.0),
 (507, 0.0),
 (508, 0.0),
 (510, 0.0),
 (511, 0.0),
 (513, 0.0),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.0),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0),
 (529, 0.0),
 (530, 0.0),
 (532, 0.0),
 (533, 0.0),
 (534, 0.0),
 (537, 0.0),
 (538, 0.0),
 (539, 0.0),
 (540, 0.0),
 (541, 0.0),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (547, 0.0),
 (548, 0.0),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (556, 0.0),
 (558, 0.0),
 (560, 0.0),
 (562, 0.0),
 (563, 0.0),
 (564, 0.0),
 (568, 0.0),
 (569, 0.0),
 (570, 0.0),
 (571, 0.0),
 (572, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.0),
 (578, 0.0),
 (579, 0.0),
 (580, 0.0),
 (584, 0.0),
 (585, 0.0),
 (586, 0.0),
 (587, 0.0),
 (588, 0.0),
 (589, 0.0),
 (590, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.0),
 (595, 0.0),
 (596, 0.0),
 (597, 0.0),
 (598, 0.0),
 (599, 0.0),
 (600, 0.0),
 (601, 0.0),
 (602, 0.0),
 (603, 0.0),
 (605, 0.0),
 (606, 0.0),
 (607, 0.0),
 (609, 0.0),
 (610, 0.0),
 (611, 0.0),
 (612, 0.0),
 (613, 0.0),
 (614, 0.0),
 (616, 0.0),
 (617, 0.0),
 (620, 0.0),
 (621, 0.0),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (626, 0.0),
 (627, 0.0),
 (628, 0.0),
 (629, 0.0),
 (630, 0.0),
 (632, 0.0),
 (633, 0.0),
 (634, 0.0),
 (635, 0.0),
 (636, 0.0),
 (637, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.0),
 (641, 0.0),
 (643, 0.0),
 (644, 0.0),
 (646, 0.0),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.0),
 (654, 0.0),
 (655, 0.0),
 (658, 0.0),
 (659, 0.0),
 (660, 0.0),
 (662, 0.0),
 (664, 0.0),
 (665, 0.0),
 (667, 0.0),
 (669, 0.0),
 (670, 0.0),
 (671, 0.0),
 (672, 0.0),
 (675, 0.0),
 (676, 0.0),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),
 (682, 0.0),
 (683, 0.0),
 (686, 0.0),
 (687, 0.0),
 (688, 0.0),
 (689, 0.0),
 (691, 0.0),
 (692, 0.0),
 (693, 0.0),
 (694, 0.0),
 (695, 0.0),
 (696, 0.0),
 (699, 0.0),
 (700, 0.0),
 (701, 0.0),
 (702, 0.0),
 (703, 0.0),
 (704, 0.0),
 (705, 0.0),
 (706, 0.0),
 (707, 0.0),
 (708, 0.0),
 (709, 0.0),
 (710, 0.0),
 (711, 0.0),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (716, 0.0),
 (717, 0.0),
 (718, 0.0),
 (720, 0.0),
 (721, 0.0),
 (722, 0.0),
 (724, 0.0),
 (726, 0.0),
 (728, 0.0),
 (729, 0.0),
 (730, 0.0),
 (732, 0.0),
 (734, 0.0),
 (735, 0.0),
 (736, 0.0),
 (738, 0.0),
 (740, 0.0),
 (741, 0.0),
 (742, 0.0),
 (744, 0.0),
 (745, 0.0),
 (746, 0.0),
 (748, 0.0),
 (749, 0.0),
 (750, 0.0),
 (751, 0.0),
 (752, 0.0),
 (753, 0.0),
 (754, 0.0),
 (755, 0.0),
 (756, 0.0),
 (757, 0.0),
 (758, 0.0),
 (759, 0.0),
 (760, 0.0),
 (761, 0.0),
 (762, 0.0),
 (763, 0.0),
 (764, 0.0),
 (765, 0.0),
 (766, 0.0),
 (767, 0.0),
 (768, 0.0),
 (769, 0.0),
 (770, 0.0),
 (772, 0.0),
 (774, 0.0),
 (775, 0.0),
 (776, 0.0),
 (777, 0.0),
 (778, 0.0),
 (779, 0.0),
 (780, 0.0),
 (781, 0.0),
 (782, 0.0),
 (783, 0.0),
 (784, 0.0),
 (785, 0.0),
 (786, 0.0),
 (787, 0.0),
 (788, 0.0),
 (789, 0.0),
 (790, 0.0),
 (791, 0.0),
 (793, 0.0),
 (794, 0.0),
 (797, 0.0),
 (798, 0.0),
 (799, 0.0),
 (800, 0.0),
 (803, 0.0),
 (805, 0.0),
 (807, 0.0),
 (808, 0.0),
 (809, 0.0),
 (810, 0.0),
 (811, 0.0),
 (812, 0.0),
 (813, 0.0),
 (814, 0.0),
 (816, 0.0),
 (817, 0.0),
 (818, 0.0),
 (819, 0.0),
 (820, 0.0),
 (821, 0.0),
 (822, 0.0),
 (823, 0.0),
 (824, 0.0),
 (825, 0.0),
 (826, 0.0),
 (829, 0.0),
 (830, 0.0),
 (831, 0.0),
 (832, 0.0),
 (833, 0.0),
 (834, 0.0),
 (835, 0.0),
 (836, 0.0),
 (837, 0.0),
 (838, 0.0),
 (839, 0.0),
 (840, 0.0),
 (842, 0.0),
 (844, 0.0),
 (847, 0.0),
 (848, 0.0),
 (849, 0.0),
 (850, 0.0),
 (851, 0.0),
 (852, 0.0),
 (853, 0.0),
 (855, 0.0),
 (856, 0.0),
 (857, 0.0),
 (858, 0.0),
 (860, 0.0),
 (861, 0.0),
 (862, 0.0),
 (863, 0.0),
 (864, 0.0),
 (867, 0.0),
 (868, 0.0),
 (869, 0.0),
 (871, 0.0),
 (872, 0.0),
 (874, 0.0),
 (875, 0.0),
 (879, 0.0),
 (880, 0.0),
 (881, 0.0),
 (882, 0.0),
 (883, 0.0),
 (884, 0.0),
 (885, 0.0),
 (886, 0.0),
 (888, 0.0),
 (890, 0.0),
 (891, 0.0),
 (892, 0.0),
 (893, 0.0),
 (894, 0.0),
 (896, 0.0),
 (898, 0.0),
 (899, 0.0),
 (900, 0.0),
 (903, 0.0),
 (906, 0.0),
 (907, 0.0),
 (908, 0.0),
 (909, 0.0),
 (911, 0.0),
 (912, 0.0),
 (914, 0.0),
 (915, 0.0),
 (916, 0.0),
 (917, 0.0),
 (918, 0.0),
 (919, 0.0),
 (920, 0.0),
 (921, 0.0),
 (922, 0.0),
 (923, 0.0),
 (924, 0.0),
 (925, 0.0),
 (926, 0.0),
 (927, 0.0),
 (928, 0.0),
 (929, 0.0),
 (930, 0.0),
 (932, 0.0),
 (934, 0.0),
 (935, 0.0),
 (937, 0.0),
 (938, 0.0),
 (940, 0.0),
 (941, 0.0),
 (942, 0.0),
 (943, 0.0),
 (944, 0.0),
 (945, 0.0),
 (946, 0.0),
 (948, 0.0),
 (949, 0.0),
 (950, 0.0),
 (951, 0.0),
 (952, 0.0),
 (953, 0.0),
 (954, 0.0),
 (955, 0.0),
 (957, 0.0),
 (958, 0.0),
 (959, 0.0),
 (960, 0.0),
 (961, 0.0),
 (962, 0.0),
 (963, 0.0),
 (964, 0.0),
 (965, 0.0),
 (966, 0.0),
 (967, 0.0),
 (968, 0.0),
 (969, 0.0),
 (970, 0.0),
 (973, 0.0),
 (974, 0.0),
 (976, 0.0),
 (979, 0.0),
 (980, 0.0),
 (981, 0.0),
 (982, 0.0),
 (983, 0.0),
 (984, 0.0),
 (985, 0.0),
 (987, 0.0),
 (988, 0.0),
 (990, 0.0),
 (991, 0.0),
 (992, 0.0),
 (993, 0.0),
 (994, 0.0),
 (995, 0.0),
 (996, 0.0),
 (997, 0.0),
 (998, 0.0),
 (999, 0.0),
 (1000, 0.0),
 (1001, 0.0),
 (1002, 0.0),
 (1003, 0.0),
 (1004, 0.0),
 (1005, 0.0),
 (1007, 0.0),
 ...]

In [184]:
users = list(matrix.index)
users

[254,
 507,
 638,
 882,
 1211,
 1424,
 1435,
 1733,
 1848,
 2033,
 2110,
 2276,
 2766,
 2891,
 2977,
 3167,
 3346,
 3363,
 3371,
 3373,
 3757,
 3827,
 4017,
 4385,
 5582,
 6073,
 6242,
 6251,
 6323,
 6543,
 6563,
 6575,
 7125,
 7158,
 7283,
 7286,
 7346,
 7915,
 8019,
 8066,
 8067,
 8245,
 8253,
 8454,
 8681,
 8734,
 9417,
 9613,
 9856,
 9908,
 10314,
 10354,
 10447,
 10560,
 11224,
 11601,
 11657,
 11676,
 11687,
 11993,
 12100,
 12538,
 12824,
 12982,
 13273,
 13518,
 13551,
 13552,
 13582,
 13850,
 13995,
 14079,
 14422,
 14456,
 14521,
 15408,
 16106,
 16634,
 16718,
 16795,
 17003,
 17183,
 17667,
 17859,
 17950,
 18067,
 18082,
 18401,
 19085,
 19493,
 19664,
 19711,
 20060,
 20115,
 20172,
 20180,
 20201,
 21011,
 21014,
 21031,
 21252,
 21364,
 21404,
 21576,
 21618,
 21659,
 22074,
 22521,
 22625,
 22818,
 23511,
 23571,
 23768,
 23871,
 23872,
 23902,
 24186,
 24194,
 24433,
 24921,
 24933,
 25409,
 25601,
 25850,
 25981,
 26084,
 26240,
 26487,
 26544,
 26593,
 26621,
 26883,
 27472,
 27617,
 27647,
 27740,
 27812,
 27875,
 28177,
 28204,
 28255,
 28523,
 28591,
 28594,
 28619,
 28634,
 28938,
 29209,
 29259,
 29526,
 29855,
 30052,
 30276,
 30445,
 30487,
 30511,
 30533,
 30711,
 30735,
 30898,
 30972,
 30985,
 30994,
 31315,
 31391,
 31393,
 31556,
 31826,
 31846,
 32250,
 32440,
 32773,
 32802,
 33124,
 33580,
 33818,
 33888,
 33974,
 34300,
 34588,
 35433,
 35445,
 35704,
 35836,
 35857,
 35859,
 35918,
 36003,
 36135,
 36256,
 36327,
 36606,
 36609,
 36715,
 36741,
 36907,
 37208,
 37293,
 37400,
 37538,
 37644,
 37712,
 37950,
 38023,
 38273,
 38281,
 38556,
 39281,
 39345,
 39396,
 39467,
 39616,
 39773,
 40415,
 40889,
 40943,
 41084,
 41449,
 41455,
 41589,
 41596,
 41757,
 41781,
 41841,
 42162,
 42323,
 42458,
 42914,
 43006,
 43246,
 43359,
 43687,
 43842,
 43910,
 44252,
 44535,
 45557,
 46145,
 46398,
 46443,
 46892,
 46909,
 47279,
 47316,
 47971,
 48025,
 48046,
 48355,
 48494,
 48911,
 49109,
 49212,
 49225,
 49422,
 49460,
 49980,
 50073,
 50225,
 50730,
 50849,
 50895,
 51252,
 51350,
 51450,
 51526,
 51883,
 51992,
 52199,
 52350,
 52584,
 52917,
 53174,
 53220,
 53241,
 53256,
 53456,
 53614,
 53729,
 54335,
 54622,
 54898,
 55075,
 55178,
 55187,
 55438,
 55490,
 55492,
 55493,
 55548,
 55734,
 55892,
 55927,
 56271,
 56307,
 56360,
 56391,
 56399,
 56447,
 56554,
 56856,
 56959,
 57398,
 57449,
 57620,
 57725,
 58067,
 58911,
 59172,
 59269,
 59656,
 59770,
 59971,
 60244,
 60263,
 60337,
 60621,
 60707,
 61028,
 61038,
 61147,
 61854,
 61901,
 61910,
 62464,
 62558,
 62862,
 62891,
 62966,
 63714,
 63854,
 63956,
 64436,
 65258,
 65584,
 66878,
 66942,
 67198,
 67547,
 67591,
 67627,
 67840,
 68128,
 68156,
 68185,
 68249,
 68383,
 68436,
 68555,
 68760,
 68984,
 69078,
 69156,
 69211,
 69232,
 69378,
 69389,
 69697,
 69933,
 69971,
 70052,
 70183,
 70415,
 70541,
 70594,
 70649,
 70666,
 71234,
 71470,
 71712,
 71739,
 71853,
 72214,
 73044,
 73394,
 73681,
 73923,
 74056,
 74286,
 74453,
 75081,
 75149,
 75485,
 75591,
 75819,
 75860,
 76151,
 76168,
 76223,
 76352,
 76482,
 76483,
 76499,
 76530,
 76626,
 76818,
 77480,
 77809,
 78448,
 78553,
 78783,
 78834,
 78846,
 78973,
 79215,
 79740,
 80071,
 80538,
 80555,
 80683,
 80810,
 80945,
 81263,
 81298,
 81368,
 81492,
 81560,
 81597,
 81682,
 81771,
 81848,
 81977,
 82407,
 82497,
 82511,
 82831,
 82893,
 83287,
 83431,
 83443,
 83637,
 83671,
 84024,
 84479,
 84882,
 85426,
 85433,
 85526,
 85757,
 85993,
 86145,
 86189,
 86202,
 86242,
 86243,
 86392,
 86835,
 87141,
 87555,
 87712,
 87911,
 87938,
 88229,
 88283,
 88412,
 88435,
 88620,
 88693,
 88733,
 88793,
 88937,
 89551,
 89602,
 89867,
 90049,
 90198,
 90616,
 91103,
 91113,
 91184,
 91631,
 92132,
 92405,
 92498,
 92810,
 92853,
 92861,
 93047,
 93092,
 93147,
 93179,
 93363,
 93426,
 93565,
 93629,
 94347,
 94730,
 94853,
 94985,
 95010,
 95025,
 95316,
 95359,
 95574,
 95903,
 95921,
 95923,
 95932,
 95991,
 96357,
 96440,
 96448,
 96554,
 96744,
 97290,
 97754,
 97874,
 98263,
 98356,
 98391,
 98440,
 98686,
 98758,
 98783,
 98787,
 98904,
 98930,
 99630,
 99720,
 99955,
 100088,
 100459,
 100578,
 100644,
 100846,
 100906,
 101209,
 101305,
 101550,
 101606,
 101620,
 101731,
 101851,
 101876,
 102275,
 102359,
 102647,
 102702,
 102967,
 103336,
 103541,
 104113,
 104144,
 104211,
 104278,
 104399,
 104429,
 104636,
 104657,
 104665,
 104880,
 105028,
 105054,
 105058,
 105221,
 105374,
 105517,
 105937,
 105979,
 106007,
 106225,
 106280,
 106768,
 107244,
 107301,
 107784,
 107951,
 108005,
 108155,
 108243,
 108285,
 108352,
 108405,
 108799,
 109574,
 109779,
 109901,
 110029,
 110076,
 110267,
 110373,
 110440,
 110912,
 110934,
 110973,
 111174,
 111190,
 111578,
 111847,
 111944,
 111947,
 112001,
 112026,
 112083,
 112093,
 112541,
 112559,
 112953,
 113030,
 113270,
 113519,
 113663,
 113904,
 113944,
 114178,
 114368,
 114414,
 114444,
 114544,
 114581,
 114865,
 114868,
 114988,
 115003,
 115435,
 115490,
 115572,
 115692,
 116758,
 116904,
 117251,
 117384,
 117873,
 118533,
 119575,
 119590,
 119858,
 120093,
 120396,
 120565,
 120598,
 120908,
 121170,
 121251,
 121606,
 122429,
 122440,
 122716,
 122793,
 123056,
 123094,
 123095,
 123154,
 123257,
 123460,
 123544,
 123608,
 123744,
 123790,
 123867,
 123883,
 123981,
 124078,
 124079,
 124363,
 124487,
 124597,
 124874,
 124876,
 125031,
 125203,
 125287,
 125411,
 125519,
 125692,
 125736,
 125774,
 126196,
 126296,
 126388,
 126492,
 126604,
 126693,
 126697,
 126736,
 126814,
 127200,
 127233,
 127826,
 128060,
 128085,
 128208,
 128434,
 128696,
 128835,
 129074,
 129084,
 129716,
 129851,
 130474,
 130482,
 130554,
 130571,
 130658,
 130705,
 130847,
 131046,
 131126,
 131154,
 131238,
 131402,
 131622,
 131855,
 132375,
 132492,
 132851,
 132930,
 133296,
 133571,
 133689,
 133747,
 134434,
 134556,
 134797,
 134837,
 135045,
 135149,
 135265,
 135351,
 135360,
 135458,
 135609,
 136139,
 136205,
 136252,
 136326,
 136348,
 136382,
 136491,
 137118,
 137190,
 137588,
 137589,
 137688,
 137742,
 138097,
 138198,
 138441,
 138543,
 138578,
 138602,
 138777,
 138844,
 138883,
 138995,
 139359,
 139742,
 139828,
 139913,
 140000,
 140036,
 140223,
 140358,
 140555,
 140662,
 140879,
 141109,
 141157,
 141444,
 141491,
 141493,
 141511,
 141710,
 141819,
 141901,
 141902,
 141958,
 142121,
 142256,
 142479,
 142524,
 142579,
 142623,
 142745,
 143163,
 143175,
 143211,
 143253,
 143415,
 143792,
 143964,
 143968,
 144038,
 144255,
 144318,
 144531,
 144555,
 145109,
 145449,
 145619,
 145641,
 146113,
 146175,
 146230,
 146348,
 146386,
 146803,
 147141,
 147224,
 147420,
 147451,
 147686,
 147839,
 147847,
 147965,
 148199,
 148258,
 148712,
 148744,
 148798,
 148898,
 149069,
 149510,
 149908,
 149934,
 150498,
 150896,
 150968,
 150979,
 151503,
 151589,
 152099,
 152186,
 152435,
 152946,
 153054,
 153361,
 153653,
 153662,
 153718,
 153797,
 154070,
 154345,
 154469,
 154529,
 154844,
 154944,
 154992,
 155014,
 155141,
 155147,
 155219,
 156150,
 156214,
 156269,
 156467,
 157247,
 157273,
 157799,
 158226,
 158254,
 158295,
 158433,
 158606,
 159033,
 159506,
 159834,
 159858,
 160295,
 160558,
 160571,
 160681,
 160819,
 161870,
 161936,
 162311,
 162639,
 162738,
 163202,
 163488,
 163570,
 163804,
 164096,
 164323,
 164581,
 164675,
 164926,
 165183,
 165308,
 165319,
 165345,
 165758,
 165759,
 166123,
 166596,
 166825,
 166922,
 167471,
 167800,
 167812,
 168047,
 168064,
 168144,
 168642,
 168954,
 169663,
 169682,
 169699,
 169735,
 169779,
 170077,
 170184,
 170513,
 170634,
 170947,
 171118,
 171295,
 171846,
 171968,
 171970,
 172061,
 172512,
 172742,
 172760,
 173415,
 173481,
 173679,
 174092,
 174216,
 174304,
 174326,
 174596,
 174791,
 174848,
 175003,
 175052,
 175101,
 175636,
 176214,
 177072,
 177090,
 177091,
 177374,
 177375,
 177432,
 177458,
 177690,
 178199,
 178201,
 178522,
 178667,
 178914,
 178920,
 179019,
 179288,
 179433,
 179718,
 179730,
 179734,
 179772,
 179791,
 179826,
 179978,
 180348,
 180651,
 180957,
 181077,
 181176,
 181687,
 182053,
 182085,
 182202,
 182334,
 182527,
 182838,
 182993,
 183046,
 183061,
 183088,
 183101,
 183187,
 183995,
 184279,
 184299,
 184365,
 184401,
 184424,
 184513,
 184532,
 185176,
 185233,
 185384,
 185634,
 185722,
 186570,
 187065,
 187145,
 187256,
 187517,
 187574,
 187624,
 187762,
 187801,
 187863,
 187904,
 188010,
 188022,
 188027,
 188273,
 188951,
 189080,
 ...]

In [185]:
book_titles = list(matrix.columns)
book_titles

['1st to Die: A Novel',
 'A Painted House',
 'A Time to Kill',
 'Angels & Demons',
 "Bridget Jones's Diary",
 'Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'Dreamcatcher',
 'Fahrenheit 451',
 'Girl with a Pearl Earring',
 'Good in Bed',
 'Hannibal',
 'Harry Potter and the Chamber of Secrets (Book 2)',
 'Harry Potter and the Goblet of Fire (Book 4)',
 'Harry Potter and the Order of the Phoenix (Book 5)',
 'Harry Potter and the Prisoner of Azkaban (Book 3)',
 "Harry Potter and the Sorcerer's Stone (Book 1)",
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
 'House of Sand and Fog',
 'Interview with the Vampire',
 'Jurassic Park',
 'Life of Pi',
 'Me Talk Pretty One Day',
 'Misery',
 'Red Dragon',
 "She's Come Undone (Oprah's Book Club (Paperback))",
 'Snow Falling on Cedars',
 'Summer Sisters',
 'The Catcher in the Rye',
 'The Chamber',
 'The Client',
 'The Da Vinci Code',
 'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
 'The Firm',
 'The Five People You Meet in Heaven',
 "The Girls' Guide to Hunting and Fishing",
 'The Joy Luck Club',
 'The Lovely Bones: A Novel',
 'The Nanny Diaries: A Novel',
 'The Notebook',
 'The Partner',
 'The Pelican Brief',
 "The Pilot's Wife : A Novel",
 'The Rainmaker',
 'The Red Tent (Bestselling Backlist)',
 'The Runaway Jury',
 'The Secret Life of Bees',
 'The Street Lawyer',
 'The Testament',
 'The Two Towers (The Lord of the Rings, Part 2)',
 'The Vampire Lestat (Vampire Chronicles, Book II)',
 'Timeline',
 'To Kill a Mockingbird',
 "Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",
 "Where the Heart Is (Oprah's Book Club (Paperback))",
 'Wild Animus']

#### The next cell will take very long to execute

In [186]:
matrix_with_pred = matrix.copy()

for user in matrix.index:
    
    user_index = np.where(matrix.index==user)[0][0]
    # print("user_index = ", user_index)

    for i in range(len(matrix.columns)):
        # print("i value = ", i)
        if matrix.isnull().iloc[user_index][i]:
            # print(f"rating of user:{user} for book {matrix.columns[i]} is null")
            k =3   # number of top similar users who have rated the book
            # print(f"k = {k}")
            count =0
            # print(f"count = {count}")
            sum_sim_mul_rat = 0
            
            sum_sim = 0
            predicted_rate = 0
            similar_user_indices_with_similarity = get_similar_users(user) 
            similar_user_indices = [x[0] for x in similar_user_indices_with_similarity]
            
            for similar_user_index,similarity in similar_user_indices_with_similarity:
                # print(f"similar user index is {similar_user_index}")
                if(count==k):
                    break
                else:
                    if matrix.isnull().iloc[similar_user_index][i]:
                        continue
                    
                    if (matrix.iloc[similar_user_index][i]==0 or similarity==0):
                        continue
                    
                    count+=1
                    sum_sim_mul_rat+= similarity*matrix.iloc[similar_user_index][i]
                    sum_sim += similarity
                    # print(f"rating of user_id {matrix.index[similar_user_index]} for book{book_index}: \"{matrix.columns[book_index]}\" is {matrix.iloc[similar_user_index][book_index]} \nsimilarity is {similarity} at count {count}") 
            if sum_sim==0:
                predicted_rate=0
            else:
                predicted_rate = sum_sim_mul_rat/sum_sim
            # print(f"for user:{user} for book:{matrix.columns[i]} predicted rate is {predicted_rate}")
            matrix_with_pred.iloc[user_index, i] = predicted_rate

In [187]:
matrix_with_pred

book_title,1st to Die: A Novel,A Painted House,A Time to Kill,Angels & Demons,Bridget Jones's Diary,Divine Secrets of the Ya-Ya Sisterhood: A Novel,Dreamcatcher,Fahrenheit 451,Girl with a Pearl Earring,Good in Bed,...,The Secret Life of Bees,The Street Lawyer,The Testament,"The Two Towers (The Lord of the Rings, Part 2)","The Vampire Lestat (Vampire Chronicles, Book II)",Timeline,To Kill a Mockingbird,"Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",Where the Heart Is (Oprah's Book Club (Paperback)),Wild Animus
user_id,,,,,,,,,,,,,,,,,,,,,
254,6.799080,7.687447,7.881521,8.268176,9.023453,5.409950,5.247926,5.866052,6.595330,8.706098,...,9.000000,7.168317,6.336404,10.000000,6.148687,7.715062,9.871263,7.263243,8.622378,3.012034
507,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
638,6.476640,8.487022,9.000000,6.929931,9.074226,8.130196,8.421249,8.966892,6.564314,8.000000,...,8.589450,6.526574,7.420650,10.000000,8.633313,6.983286,9.389895,8.248560,8.434142,3.173206
882,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1211,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277427,8.853151,9.341568,7.255612,9.027452,7.438965,9.136695,8.673235,9.060138,8.802730,8.324801,...,9.565050,7.598496,6.754393,10.062470,7.012114,9.001098,8.748748,9.666383,8.445592,4.896796
278137,5.000000,7.762682,7.877486,7.833903,8.278207,6.914016,5.000000,8.154701,7.054441,8.026511,...,7.347718,7.146975,8.369222,10.000000,8.882674,8.147529,8.735187,9.211543,7.529297,2.800659
278188,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
278356,7.172422,8.797535,8.146085,8.000000,9.385163,6.792045,5.000000,7.975314,10.000000,9.417396,...,8.465904,8.000000,7.656969,9.524327,8.149267,8.084642,9.189466,6.833820,8.652611,1.338879
278633,9.035925,9.350984,10.000000,8.158491,2.000000,8.354423,6.354102,9.100952,7.242632,7.412137,...,9.003597,7.100840,7.389749,8.928655,9.265069,5.822120,10.000000,8.782568,8.727180,4.449490

In [188]:
matrix_with_pred.to_csv("Predicted Ratings Matrix with index.csv")
matrix_with_pred.to_csv("Predicted Ratings Matrix without index.csv")