In [289]:
import numpy as np
import pandas as pd

## Exploratory Data Analysis

In [290]:
data = pd.read_csv("book ratings dataset/Books Data with Category Language and Summary/Preprocessed_data.csv")

In [291]:
data

,Unnamed: 0,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
0,0,2,"stockton, california, usa",18.0000,0195153448,0,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,Provides an introduction to classical myths pl...,en,['Social Science'],stockton,california,usa
1,1,8,"timmins, ontario, canada",34.7439,0002005018,5,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],timmins,ontario,canada
2,2,11400,"ottawa, ontario, canada",49.0000,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,ontario,canada
3,3,11676,"n/a, n/a, n/a",34.7439,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],NaN,NaN,NaN
4,4,41385,"sudbury, ontario, canada",34.7439,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],sudbury,ontario,canada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031170,1031170,278851,"dallas, texas, usa",33.0000,0743203763,0,As Hogan Said . . . : The 389 Best Things Anyo...,Randy Voorhees,2000.0,Simon & Schuster,http://images.amazon.com/images/P/0743203763.0...,http://images.amazon.com/images/P/0743203763.0...,http://images.amazon.com/images/P/0743203763.0...,Golf lovers will revel in this collection of t...,en,['Humor'],dallas,texas,usa
1031171,1031171,278851,"dallas, texas, usa",33.0000,0767907566,5,All Elevations Unknown: An Adventure in the He...,Sam Lightner,2001.0,Broadway Books,http://images.amazon.com/images/P/0767907566.0...,http://images.amazon.com/images/P/0767907566.0...,http://images.amazon.com/images/P/0767907566.0...,A daring twist on the travel-adventure genre t...,en,['Nature'],dallas,texas,usa
1031172,1031172,278851,"dallas, texas, usa",33.0000,0884159221,7,Why stop?: A guide to Texas historical roadsid...,Claude Dooley,1985.0,Lone Star Books,http://images.amazon.com/images/P/0884159221.0...,http://images.amazon.com/images/P/0884159221.0...,http://images.amazon.com/images/P/0884159221.0...,9,9,9,dallas,texas,usa
1031173,1031173,278851,"dallas, texas, usa",33.0000,0912333022,7,The Are You Being Served? Stories: 'Camping In...,Jeremy Lloyd,1997.0,Kqed Books,http://images.amazon.com/images/P/0912333022.0...,http://images.amazon.com/images/P/0912333022.0...,http://images.amazon.com/images/P/0912333022.0...,These hilarious stories by the creator of publ...,en,['Fiction'],dallas,texas,usa
1031174,1031174,278851,"dallas, texas, usa",33.0000,1569661057,10,"Dallas Street Map Guide and Directory, 2000 Ed...",Mapsco,1999.0,American Map Corporation,http://images.amazon.com/images/P/1569661057.0...,http://images.amazon.com/images/P/1569661057.0...,http://images.amazon.com/images/P/1569661057.0...,9,9,9,dallas,texas,usa

In [292]:
data.drop(columns=["Unnamed: 0"], inplace=True)
data.head()

,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
0,2,"stockton, california, usa",18.0000,0195153448,0,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,Provides an introduction to classical myths pl...,en,['Social Science'],stockton,california,usa
1,8,"timmins, ontario, canada",34.7439,0002005018,5,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],timmins,ontario,canada
2,11400,"ottawa, ontario, canada",49.0000,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,ontario,canada
3,11676,"n/a, n/a, n/a",34.7439,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],NaN,NaN,NaN
4,41385,"sudbury, ontario, canada",34.7439,0002005018,0,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],sudbury,ontario,canada

In [293]:
data.shape

(1031175, 18)

In [294]:
data  = data[data['rating'] != 0]

In [295]:
data.shape

(383852, 18)

In [296]:
data.groupby("book_title").count()["rating"].reset_index().sort_values(by="rating", ascending=False)

                                               book_title  rating
110234                          The Lovely Bones: A Novel     707
132246                                        Wild Animus     581
102707                                  The Da Vinci Code     494
116201                            The Secret Life of Bees     406
111955                         The Nanny Diaries: A Novel     393
...                                                   ...     ...
54565                             Journeys to Door County       1
54563   Journeys of Simplicity: Traveling Light With T...       1
54562                            Journeys into Past Lives       1
54561   Journeys down the line: Building the Trans-Ala...       1
135572                                  Ã?Â?thique en toc       1

[135573 rows x 2 columns]

In [297]:
data.groupby("user_id").count()["rating"].reset_index().sort_values(by="rating", ascending=False)

       user_id  rating
2719     11676    6943
24101    98391    5691
46279   189835    1899
37648   153662    1845
5615     23902    1180
...        ...     ...
33246   135660       1
33250   135677       1
33252   135684       1
6297     26542       1
34046   138846       1

[68092 rows x 2 columns]

In [298]:
x = data.groupby("user_id").count()["rating"] > 10
significant_users = x[x].index
significant_users

Int64Index([   242,    243,    254,    388,    392,    446,    503,    505,
               507,    638,
            ...
            278221, 278356, 278390, 278418, 278535, 278554, 278582, 278633,
            278843, 278851],
           dtype='int64', name='user_id', length=5981)

In [299]:
data_modified = data[data["user_id"].isin(significant_users)]
data_modified

,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
3,11676,"n/a, n/a, n/a",34.7439,0002005018,8,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],NaN,NaN,NaN
8,116866,"ottawa, ,",34.7439,0002005018,9,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],ottawa,",",NaN
13,219008,"halifax, nova scotia, canada",60.0000,0002005018,7,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],halifax,nova scotia,canada
14,263325,"fredericton, new brunswick, canada",27.0000,0002005018,6,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses'],fredericton,new brunswick,canada
16,2954,"wichita, kansas, usa",71.0000,0060973129,8,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,"Here, for the first time in paperback, is an o...",en,['1940-1949'],wichita,kansas,usa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031169,278851,"dallas, texas, usa",33.0000,067161746X,7,The Bachelor Home Companion: A Practical Guide...,P.J. O'Rourke,1987.0,Pocket Books,http://images.amazon.com/images/P/067161746X.0...,http://images.amazon.com/images/P/067161746X.0...,http://images.amazon.com/images/P/067161746X.0...,A tongue-in-cheek survival guide for single pe...,en,['Humor'],dallas,texas,usa
1031171,278851,"dallas, texas, usa",33.0000,0767907566,5,All Elevations Unknown: An Adventure in the He...,Sam Lightner,2001.0,Broadway Books,http://images.amazon.com/images/P/0767907566.0...,http://images.amazon.com/images/P/0767907566.0...,http://images.amazon.com/images/P/0767907566.0...,A daring twist on the travel-adventure genre t...,en,['Nature'],dallas,texas,usa
1031172,278851,"dallas, texas, usa",33.0000,0884159221,7,Why stop?: A guide to Texas historical roadsid...,Claude Dooley,1985.0,Lone Star Books,http://images.amazon.com/images/P/0884159221.0...,http://images.amazon.com/images/P/0884159221.0...,http://images.amazon.com/images/P/0884159221.0...,9,9,9,dallas,texas,usa
1031173,278851,"dallas, texas, usa",33.0000,0912333022,7,The Are You Being Served? Stories: 'Camping In...,Jeremy Lloyd,1997.0,Kqed Books,http://images.amazon.com/images/P/0912333022.0...,http://images.amazon.com/images/P/0912333022.0...,http://images.amazon.com/images/P/0912333022.0...,These hilarious stories by the creator of publ...,en,['Fiction'],dallas,texas,usa
1031174,278851,"dallas, texas, usa",33.0000,1569661057,10,"Dallas Street Map Guide and Directory, 2000 Ed...",Mapsco,1999.0,American Map Corporation,http://images.amazon.com/images/P/1569661057.0...,http://images.amazon.com/images/P/1569661057.0...,http://images.amazon.com/images/P/1569661057.0...,9,9,9,dallas,texas,usa

In [300]:
data_modified.groupby("isbn").count()["rating"].reset_index().sort_values(by="rating", ascending=False)

              isbn  rating
17953   0316666343     319
32398   0385504209     268
14646   0312195516     185
57812   059035342X     177
97357   0971880107     171
...            ...     ...
49101   0486259978       1
49100   0486259285       1
49099   0486259250       1
49098   0486258521       1
119494  B000234N3A       1

[119495 rows x 2 columns]

In [301]:
y = data_modified.groupby("isbn").count()["rating"] >=50
significant_books = y[y].index

In [302]:
data_modified = data_modified[data_modified["isbn"].isin(significant_books)]
data_modified

,user_id,location,age,isbn,rating,book_title,book_author,year_of_publication,publisher,img_s,img_m,img_l,Summary,Language,Category,city,state,country
102,3329,"grantsville, utah, usa",34.7439,0440234743,8,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],grantsville,utah,usa
106,7346,"sunnyvale, california, usa",49.0000,0440234743,9,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],sunnyvale,california,usa
107,7352,"houston, texas, usa",53.0000,0440234743,8,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],houston,texas,usa
111,11224,"tumwater, washington, usa",51.0000,0440234743,6,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],tumwater,washington,usa
112,11676,"n/a, n/a, n/a",34.7439,0440234743,9,The Testament,John Grisham,1999.0,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,"A suicidal billionaire, a burnt-out Washington...",en,['Fiction'],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340514,270605,"bourbonnais, illinois, usa",34.7439,0684801523,6,The Great Gatsby,F. Scott Fitzgerald,1995.0,Scribner,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,9,9,9,bourbonnais,illinois,usa
340518,273976,"saratoga, california, usa",20.0000,0684801523,3,The Great Gatsby,F. Scott Fitzgerald,1995.0,Scribner,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,9,9,9,saratoga,california,usa
340519,274301,"frankston, victoria, australia",41.0000,0684801523,7,The Great Gatsby,F. Scott Fitzgerald,1995.0,Scribner,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,9,9,9,frankston,victoria,australia
340520,275020,"new york, new york, usa",34.7439,0684801523,6,The Great Gatsby,F. Scott Fitzgerald,1995.0,Scribner,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,9,9,9,new york,new york,usa
340521,275306,"tyler, texas, usa",24.0000,0684801523,10,The Great Gatsby,F. Scott Fitzgerald,1995.0,Scribner,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,http://images.amazon.com/images/P/0684801523.0...,9,9,9,tyler,texas,usa

## Matrix of books against users

In [303]:
matrix = data_modified.pivot_table(index="user_id", columns="isbn", values="rating")
matrix

isbn,0060392452,0060502258,0060915544,0060928336,0060930535,0060934417,0060938455,0060959037,0060976845,0060987103,...,0842329129,0842329218,0842329242,0971880107,1400031354,1400034779,155874262X,1558743669,1573225789,1573229326
user_id,,,,,,,,,,,,,,,,,,,,,
243,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN
505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278535,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
278633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [304]:
def subtract_row_mean(row):
    row_mean = np.nanmean(row)  # Calculate the mean excluding NaN values
    return row.apply(lambda x: x - row_mean if not np.isnan(x) else x)

# Apply the function to each row of the DataFrame
matrix_normalized = matrix.apply(subtract_row_mean, axis=1)



# Display the resulting DataFrame
matrix_normalized

isbn,0060392452,0060502258,0060915544,0060928336,0060930535,0060934417,0060938455,0060959037,0060976845,0060987103,...,0842329129,0842329218,0842329242,0971880107,1400031354,1400034779,155874262X,1558743669,1573225789,1573229326
user_id,,,,,,,,,,,,,,,,,,,,,
243,NaN,NaN,2.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-2.833333,NaN,NaN,NaN
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278535,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
278633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [305]:
matrix_normalized.fillna(0, inplace=True)

In [306]:
matrix_normalized

isbn,0060392452,0060502258,0060915544,0060928336,0060930535,0060934417,0060938455,0060959037,0060976845,0060987103,...,0842329129,0842329218,0842329242,0971880107,1400031354,1400034779,155874262X,1558743669,1573225789,1573229326
user_id,,,,,,,,,,,,,,,,,,,,,
243,0.0,0.0,2.166667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-2.833333,0.0,0.0,0.0
254,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
388,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,-1.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
503,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
505,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278418,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
278535,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
278582,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.000000,0.0,0.0,0.0
278633,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
278843,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0

# Making user clusters based on user-user collaborative filtering using common book ratings

In [307]:
from sklearn.metrics.pairwise import cosine_similarity

In [308]:
user_similarity = cosine_similarity(matrix_normalized)

In [309]:
user_similarity

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.17924429],
       [0.        , 0.        , 0.        , ..., 0.        , 0.17924429,
        1.        ]])

In [310]:
user_similarity.shape

(4050, 4050)

In [311]:
def get_similar_users(user_id, suggestion_num):
    index = np.where(matrix.index==user_id)[0][0]
    neareset_neighbours = sorted(list(enumerate(user_similarity[index])), key=lambda x:x[1], reverse=True)[1:] # suggestion_num+1
    return neareset_neighbours

In [312]:
similar_user_indices_with_similarity = get_similar_users(254, 0) # 0 in the parameter does not mean anything, not getting used
similar_user_indices = [x[0] for x in similar_user_indices_with_similarity]
similar_user_indices

[2963,
 2561,
 2183,
 1091,
 630,
 333,
 1065,
 2154,
 2310,
 3180,
 1563,
 2255,
 1494,
 78,
 2956,
 1241,
 1347,
 2705,
 3135,
 2832,
 2859,
 816,
 2409,
 1108,
 1295,
 2225,
 2406,
 198,
 612,
 1447,
 352,
 1725,
 2977,
 1507,
 1164,
 2765,
 2300,
 2322,
 2060,
 780,
 1018,
 1147,
 3163,
 3375,
 3502,
 2605,
 905,
 1079,
 618,
 860,
 2429,
 1319,
 795,
 301,
 1442,
 3716,
 1758,
 430,
 3427,
 2526,
 820,
 2397,
 3047,
 3173,
 471,
 3535,
 1920,
 3139,
 1122,
 2393,
 1791,
 2158,
 3370,
 1578,
 3872,
 1877,
 1474,
 4020,
 2601,
 289,
 1244,
 3478,
 1317,
 3854,
 849,
 1764,
 189,
 2351,
 3551,
 280,
 1055,
 803,
 3004,
 1658,
 2290,
 2722,
 3965,
 738,
 954,
 1691,
 2740,
 579,
 690,
 2822,
 3244,
 1841,
 884,
 111,
 3834,
 2013,
 382,
 1029,
 2697,
 1145,
 796,
 515,
 3087,
 2952,
 3707,
 1780,
 518,
 74,
 163,
 24,
 4011,
 1587,
 1782,
 85,
 285,
 390,
 651,
 693,
 951,
 1044,
 1063,
 1160,
 1425,
 1749,
 1797,
 1912,
 2169,
 2194,
 2335,
 2559,
 2652,
 2795,
 2954,
 3017,
 3166,
 3570,
 3895,
 4004,
 1463,
 3008,
 2068,
 1437,
 2226,
 1747,
 3376,
 3340,
 2686,
 2445,
 2483,
 1513,
 3061,
 3264,
 2481,
 2177,
 712,
 3560,
 2826,
 3363,
 1397,
 3788,
 103,
 2897,
 136,
 1264,
 1307,
 2584,
 982,
 1066,
 1771,
 2441,
 3225,
 2206,
 2993,
 3277,
 110,
 2045,
 2583,
 3951,
 2248,
 1553,
 1210,
 562,
 966,
 2523,
 3935,
 2331,
 2367,
 675,
 92,
 1663,
 1090,
 1836,
 1985,
 2229,
 2569,
 2683,
 2694,
 3157,
 1833,
 128,
 3495,
 3490,
 767,
 3462,
 3882,
 3482,
 2281,
 3803,
 2656,
 1379,
 2147,
 2817,
 2629,
 3068,
 1073,
 2235,
 3184,
 319,
 2624,
 2029,
 3075,
 3204,
 2162,
 485,
 1006,
 1196,
 2724,
 881,
 154,
 3829,
 1222,
 3985,
 2035,
 2282,
 1100,
 3598,
 1988,
 1500,
 3635,
 3356,
 413,
 3499,
 1060,
 2647,
 2403,
 1673,
 628,
 1600,
 1531,
 3432,
 3723,
 1887,
 3530,
 2760,
 3939,
 3161,
 3647,
 2824,
 340,
 3224,
 1243,
 522,
 3202,
 32,
 3651,
 3117,
 3762,
 2467,
 249,
 3428,
 1075,
 3140,
 1599,
 2252,
 2405,
 2594,
 2292,
 3228,
 201,
 3553,
 2842,
 1564,
 2803,
 3219,
 826,
 3454,
 798,
 1869,
 2141,
 2185,
 3022,
 3408,
 2387,
 2463,
 3517,
 1005,
 1046,
 866,
 1372,
 2330,
 513,
 3129,
 3581,
 351,
 2910,
 2718,
 2620,
 3523,
 3106,
 77,
 3835,
 3519,
 1076,
 171,
 468,
 487,
 3019,
 3051,
 109,
 789,
 281,
 3377,
 683,
 3540,
 3020,
 1966,
 2402,
 3563,
 1979,
 2903,
 3094,
 1832,
 558,
 2617,
 2509,
 957,
 3905,
 2658,
 2798,
 3044,
 3154,
 403,
 1353,
 447,
 3853,
 1556,
 1865,
 346,
 3401,
 1148,
 1360,
 3865,
 3522,
 869,
 2461,
 819,
 973,
 2874,
 2218,
 292,
 989,
 2152,
 977,
 1449,
 548,
 1506,
 3379,
 1550,
 1078,
 80,
 3740,
 3336,
 2008,
 2493,
 3752,
 1895,
 0,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 25,
 27,
 28,
 29,
 30,
 31,
 34,
 35,
 36,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 72,
 73,
 75,
 76,
 79,
 81,
 82,
 83,
 84,
 86,
 87,
 88,
 89,
 90,
 91,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 104,
 105,
 108,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 130,
 131,
 132,
 133,
 134,
 135,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 150,
 152,
 153,
 155,
 156,
 157,
 159,
 160,
 162,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 190,
 191,
 193,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 219,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 232,
 233,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 282,
 283,
 284,
 286,
 287,
 288,
 290,
 291,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 302,
 303,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 316,
 317,
 318,
 321,
 322,
 323,
 324,
 325,
 327,
 328,
 329,
 330,
 331,
 332,
 334,
 335,
 336,
 337,
 338,
 339,
 341,
 342,
 343,
 344,
 345,
 348,
 349,
 350,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 404,
 405,
 407,
 408,
 409,
 410,
 411,
 412,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 429,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 448,
 449,
 450,
 451,
 452,
 453,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 469,
 470,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 486,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 514,
 516,
 517,
 519,
 520,
 521,
 523,
 524,
 525,
 526,
 527,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 549,
 550,
 552,
 553,
 555,
 556,
 557,
 559,
 560,
 561,
 563,
 564,
 565,
 566,
 567,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 609,
 610,
 611,
 613,
 614,
 615,
 616,
 617,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 629,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 646,
 647,
 648,
 649,
 650,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 684,
 685,
 686,
 687,
 688,
 689,
 691,
 692,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 ...]

In [313]:
users = list(matrix.index)
users

[243,
 254,
 388,
 503,
 505,
 507,
 638,
 709,
 805,
 882,
 900,
 929,
 1025,
 1131,
 1211,
 1424,
 1435,
 1548,
 1585,
 1674,
 1733,
 1848,
 1903,
 2030,
 2033,
 2110,
 2179,
 2276,
 2288,
 2337,
 2766,
 2799,
 2891,
 2977,
 3145,
 3167,
 3329,
 3346,
 3363,
 3371,
 3373,
 3556,
 3640,
 3827,
 3840,
 3923,
 4017,
 4092,
 4131,
 4157,
 4221,
 4334,
 4385,
 4600,
 4622,
 4785,
 4795,
 4938,
 5037,
 5385,
 5439,
 5476,
 5539,
 5582,
 5899,
 5903,
 5956,
 6073,
 6115,
 6238,
 6242,
 6251,
 6280,
 6323,
 6431,
 6532,
 6537,
 6543,
 6563,
 6566,
 6575,
 6577,
 6611,
 6772,
 7082,
 7105,
 7125,
 7134,
 7158,
 7283,
 7286,
 7312,
 7346,
 7352,
 7371,
 7426,
 7620,
 7841,
 7864,
 7887,
 7915,
 7958,
 8019,
 8066,
 8067,
 8234,
 8245,
 8253,
 8362,
 8454,
 8529,
 8681,
 8734,
 8782,
 8801,
 8864,
 8870,
 8872,
 8935,
 8936,
 8937,
 9177,
 9227,
 9354,
 9417,
 9574,
 9613,
 9747,
 9856,
 9908,
 10030,
 10118,
 10199,
 10314,
 10354,
 10447,
 10560,
 10590,
 10819,
 10949,
 11179,
 11224,
 11245,
 11362,
 11400,
 11601,
 11629,
 11638,
 11657,
 11676,
 11687,
 11718,
 11724,
 11788,
 11916,
 11944,
 11993,
 12100,
 12154,
 12194,
 12272,
 12538,
 12569,
 12824,
 12863,
 12917,
 12982,
 12990,
 13082,
 13093,
 13126,
 13273,
 13279,
 13280,
 13518,
 13552,
 13582,
 13664,
 13850,
 13995,
 14049,
 14079,
 14180,
 14232,
 14374,
 14387,
 14422,
 14449,
 14451,
 14456,
 14461,
 14521,
 14667,
 14744,
 14768,
 15049,
 15135,
 15185,
 15408,
 15418,
 15497,
 15602,
 15651,
 15819,
 15957,
 16009,
 16106,
 16121,
 16155,
 16246,
 16263,
 16417,
 16488,
 16504,
 16545,
 16599,
 16601,
 16634,
 16718,
 16781,
 16795,
 16916,
 16943,
 16996,
 16999,
 17003,
 17177,
 17183,
 17190,
 17282,
 17402,
 17667,
 17761,
 17859,
 17906,
 17950,
 18067,
 18082,
 18095,
 18096,
 18155,
 18172,
 18254,
 18309,
 18311,
 18401,
 18439,
 19085,
 19145,
 19336,
 19422,
 19493,
 19571,
 19573,
 19664,
 19681,
 19711,
 19760,
 19842,
 19969,
 19972,
 19974,
 20060,
 20115,
 20172,
 20180,
 20201,
 20245,
 20265,
 20294,
 20332,
 20336,
 20347,
 20401,
 20462,
 20561,
 20680,
 20703,
 20961,
 20971,
 21011,
 21014,
 21031,
 21202,
 21229,
 21252,
 21356,
 21364,
 21370,
 21404,
 21484,
 21540,
 21576,
 21618,
 21659,
 21708,
 21875,
 22045,
 22062,
 22074,
 22107,
 22252,
 22365,
 22521,
 22625,
 22813,
 22818,
 22912,
 23288,
 23408,
 23511,
 23547,
 23571,
 23652,
 23680,
 23699,
 23768,
 23771,
 23871,
 23872,
 23902,
 23933,
 24105,
 24186,
 24188,
 24194,
 24433,
 24525,
 24627,
 24641,
 24838,
 24846,
 24878,
 24921,
 24934,
 24995,
 25103,
 25131,
 25253,
 25395,
 25409,
 25410,
 25545,
 25583,
 25601,
 25827,
 25850,
 25919,
 25930,
 25966,
 25981,
 26057,
 26084,
 26209,
 26231,
 26240,
 26371,
 26487,
 26517,
 26535,
 26544,
 26553,
 26583,
 26593,
 26598,
 26620,
 26621,
 26624,
 26713,
 26756,
 26774,
 26883,
 27313,
 27462,
 27472,
 27617,
 27647,
 27740,
 27788,
 27812,
 27875,
 27947,
 28016,
 28150,
 28177,
 28204,
 28222,
 28255,
 28360,
 28451,
 28481,
 28523,
 28591,
 28594,
 28619,
 28634,
 28667,
 28735,
 28865,
 28938,
 28945,
 29101,
 29209,
 29259,
 29306,
 29497,
 29526,
 29539,
 29570,
 29855,
 29905,
 30035,
 30052,
 30081,
 30273,
 30276,
 30319,
 30333,
 30445,
 30487,
 30495,
 30511,
 30531,
 30533,
 30555,
 30590,
 30594,
 30667,
 30711,
 30716,
 30735,
 30770,
 30795,
 30806,
 30898,
 30939,
 30972,
 30985,
 30994,
 31008,
 31040,
 31094,
 31226,
 31308,
 31315,
 31343,
 31391,
 31393,
 31412,
 31471,
 31556,
 31594,
 31609,
 31652,
 31826,
 31846,
 31860,
 31919,
 31948,
 31950,
 32034,
 32110,
 32122,
 32148,
 32188,
 32195,
 32250,
 32329,
 32440,
 32516,
 32569,
 32599,
 32627,
 32721,
 32773,
 32802,
 33004,
 33124,
 33179,
 33200,
 33307,
 33319,
 33474,
 33491,
 33517,
 33580,
 33816,
 33818,
 33862,
 33888,
 33933,
 33958,
 33974,
 33999,
 34075,
 34215,
 34300,
 34377,
 34588,
 34597,
 34636,
 34752,
 34932,
 34987,
 35148,
 35188,
 35233,
 35445,
 35704,
 35718,
 35793,
 35836,
 35857,
 35859,
 35918,
 36003,
 36043,
 36135,
 36256,
 36326,
 36327,
 36554,
 36606,
 36609,
 36673,
 36715,
 36741,
 36749,
 36807,
 36817,
 36907,
 36938,
 36978,
 37208,
 37227,
 37235,
 37239,
 37293,
 37310,
 37311,
 37400,
 37493,
 37512,
 37538,
 37556,
 37573,
 37623,
 37644,
 37712,
 37790,
 37874,
 37950,
 37968,
 37974,
 37989,
 38023,
 38034,
 38273,
 38281,
 38464,
 38556,
 38590,
 38703,
 38718,
 38802,
 38887,
 38933,
 38950,
 38995,
 39159,
 39195,
 39227,
 39281,
 39345,
 39396,
 39441,
 39467,
 39502,
 39513,
 39616,
 39646,
 39773,
 40222,
 40316,
 40330,
 40415,
 40466,
 40505,
 40612,
 40640,
 40796,
 40798,
 40838,
 40888,
 40889,
 40914,
 40943,
 41080,
 41084,
 41111,
 41177,
 41364,
 41403,
 41449,
 41455,
 41589,
 41596,
 41757,
 41760,
 41781,
 41841,
 41911,
 42093,
 42099,
 42162,
 42323,
 42372,
 42410,
 42419,
 42458,
 42597,
 42718,
 42798,
 42902,
 42948,
 43004,
 43006,
 43093,
 43163,
 43246,
 43282,
 43359,
 43397,
 43436,
 43481,
 43619,
 43642,
 43687,
 43698,
 43806,
 43842,
 43901,
 43910,
 43920,
 43925,
 44252,
 44297,
 44389,
 44472,
 44535,
 44611,
 44727,
 44728,
 44842,
 44845,
 44852,
 44893,
 44925,
 45042,
 45064,
 45068,
 45315,
 45340,
 45383,
 45416,
 45418,
 45557,
 45778,
 45899,
 46099,
 46145,
 46154,
 46269,
 46389,
 46398,
 46443,
 46461,
 46892,
 46909,
 47118,
 47128,
 47152,
 47279,
 47316,
 47856,
 47971,
 47975,
 48025,
 48037,
 48046,
 48213,
 48217,
 48268,
 48355,
 48474,
 48494,
 48579,
 48630,
 48743,
 48911,
 48970,
 48975,
 48995,
 49109,
 49154,
 49155,
 49212,
 49225,
 49262,
 49314,
 49392,
 49422,
 49460,
 49771,
 49792,
 49842,
 49980,
 50073,
 50204,
 50205,
 50225,
 50612,
 50615,
 50681,
 50730,
 50849,
 50895,
 51207,
 51252,
 51350,
 51359,
 51364,
 51365,
 51450,
 51526,
 51742,
 51803,
 51826,
 51856,
 51883,
 51992,
 52002,
 52021,
 52044,
 52159,
 52175,
 52199,
 52256,
 52293,
 52350,
 52521,
 52584,
 52853,
 52917,
 52994,
 53042,
 53069,
 53174,
 53220,
 53241,
 53256,
 53278,
 53304,
 53332,
 53392,
 53414,
 53418,
 53456,
 53575,
 53590,
 53614,
 53628,
 53729,
 53846,
 54005,
 54193,
 54335,
 54453,
 54605,
 54622,
 54652,
 54884,
 54898,
 54997,
 55006,
 55027,
 55075,
 55097,
 55142,
 55178,
 55187,
 55272,
 55398,
 55438,
 55487,
 55490,
 55492,
 55493,
 55548,
 55607,
 55734,
 55751,
 55789,
 55799,
 55858,
 55892,
 55927,
 56157,
 56271,
 56272,
 56307,
 56360,
 56391,
 56399,
 56447,
 56470,
 56554,
 56804,
 56856,
 56959,
 57095,
 57105,
 57108,
 57234,
 57305,
 57369,
 57398,
 57449,
 57599,
 57620,
 57713,
 57725,
 57976,
 58062,
 58067,
 58142,
 58224,
 58255,
 58342,
 58351,
 58363,
 58389,
 58529,
 58594,
 58612,
 58855,
 58911,
 59038,
 59150,
 59172,
 59189,
 59209,
 59267,
 59269,
 59305,
 59390,
 59504,
 59524,
 59612,
 59656,
 59727,
 59770,
 59912,
 59933,
 59971,
 60029,
 60050,
 60079,
 60168,
 60244,
 60251,
 60263,
 60307,
 60337,
 60392,
 60424,
 60427,
 60445,
 60475,
 60546,
 60569,
 60583,
 60621,
 60703,
 60707,
 60941,
 61028,
 61038,
 61042,
 61147,
 61257,
 61296,
 61427,
 61619,
 61704,
 61798,
 61854,
 61901,
 61910,
 62172,
 62239,
 62272,
 62316,
 62464,
 62542,
 62558,
 62862,
 62881,
 62891,
 62895,
 62966,
 63004,
 63360,
 63389,
 63394,
 63507,
 63625,
 63854,
 63923,
 63938,
 63956,
 64241,
 64270,
 64310,
 64396,
 64435,
 64436,
 64535,
 64679,
 64763,
 65032,
 65145,
 65191,
 65208,
 65228,
 65238,
 65258,
 65484,
 65549,
 65584,
 65663,
 65710,
 65769,
 65791,
 65877,
 66073,
 66323,
 66387,
 66443,
 66518,
 66574,
 66640,
 66680,
 66789,
 66878,
 66942,
 67085,
 67198,
 67270,
 67288,
 67296,
 67354,
 67402,
 67415,
 67515,
 67542,
 67547,
 67591,
 67627,
 67663,
 67840,
 67930,
 68000,
 68128,
 68156,
 68185,
 68249,
 68256,
 68383,
 68436,
 68555,
 68568,
 68760,
 68846,
 68886,
 68943,
 68984,
 69023,
 69042,
 69078,
 69156,
 69188,
 69211,
 69232,
 69252,
 69355,
 69378,
 69389,
 69405,
 69554,
 ...]

In [314]:
isbns = list(matrix.columns)
isbns

['0060392452',
 '0060502258',
 '0060915544',
 '0060928336',
 '0060930535',
 '0060934417',
 '0060938455',
 '0060959037',
 '0060976845',
 '0060987103',
 '0060987529',
 '0060987561',
 '0061009059',
 '006101351X',
 '0062502182',
 '0064407667',
 '0070212570',
 '0140067477',
 '014025448X',
 '014028009X',
 '0140293248',
 '014029628X',
 '0140298479',
 '0142000205',
 '0142001430',
 '0142001740',
 '0151008116',
 '0156027321',
 '0312195516',
 '0312278586',
 '0312291639',
 '0312305060',
 '0312924585',
 '0312966091',
 '0312966970',
 '0312971346',
 '0312976275',
 '0312980140',
 '0312983271',
 '0312990456',
 '0316096199',
 '0316284955',
 '0316569321',
 '0316601950',
 '0316666343',
 '0316769487',
 '0316776963',
 '0345313860',
 '0345337662',
 '0345339681',
 '0345339703',
 '0345339711',
 '0345339738',
 '0345342968',
 '0345350499',
 '0345351525',
 '0345353145',
 '0345361792',
 '0345370775',
 '0345378490',
 '0345380371',
 '0345384466',
 '034538475X',
 '0345387651',
 '034540288X',
 '0345417623',
 '0345438329',
 '0345439104',
 '0345443284',
 '0375700757',
 '0375706771',
 '0375707972',
 '0375725784',
 '0375726403',
 '0375727345',
 '0380002930',
 '0380718340',
 '0380731851',
 '0380789019',
 '0380789035',
 '038079487X',
 '0385265700',
 '0385335482',
 '0385335881',
 '0385484518',
 '0385486804',
 '0385492081',
 '0385504209',
 '0385505833',
 '0385720106',
 '0385722206',
 '0399501487',
 '0425147622',
 '0425154092',
 '0439064864',
 '0439064872',
 '0439136350',
 '0439136369',
 '0439139597',
 '0439139600',
 '043935806X',
 '0440206154',
 '044021145X',
 '0440211727',
 '0440212561',
 '0440213525',
 '0440214041',
 '0440215625',
 '0440220602',
 '0440221471',
 '044022165X',
 '0440222656',
 '0440224675',
 '0440224764',
 '0440225701',
 '0440226104',
 '0440226430',
 '0440234743',
 '0440236673',
 '044023722X',
 '0440241073',
 '0440498058',
 '0446310786',
 '0446364193',
 '044651652X',
 '0446532231',
 '0446601241',
 '0446605239',
 '0446606812',
 '0446607657',
 '0446608955',
 '0446610038',
 '0446611212',
 '0446611867',
 '0446612790',
 '0446670251',
 '0446672211',
 '0449005615',
 '0449212602',
 '0449219364',
 '0451156609',
 '0451167317',
 '0451169530',
 '0451184963',
 '0451524934',
 '0451526341',
 '0452264464',
 '0452282152',
 '0452282829',
 '0515131229',
 '0515132020',
 '051513287X',
 '0553250426',
 '0553271636',
 '0553279912',
 '0553280341',
 '0553296981',
 '0553572997',
 '0590353403',
 '059035342X',
 '0609804138',
 '0671001795',
 '0671003755',
 '0671021001',
 '067102423X',
 '0671027360',
 '0671027387',
 '0671041789',
 '0671510053',
 '0679429220',
 '0679745203',
 '0679746048',
 '067976402X',
 '0684801523',
 '068484267X',
 '068484477X',
 '0684872153',
 '0684874350',
 '0743227441',
 '0743237188',
 '0743418174',
 '0767905180',
 '0786817070',
 '0786868716',
 '0786881852',
 '080410526X',
 '0804106304',
 '080410753X',
 '0804114986',
 '0805063897',
 '0812550706',
 '0842329129',
 '0842329218',
 '0842329242',
 '0971880107',
 '1400031354',
 '1400034779',
 '155874262X',
 '1558743669',
 '1573225789',
 '1573229326']

In [328]:
def get_rating_prediction(user_id, isbn):
    if user_id in matrix.index and isbn in matrix.columns:
        user_index = np.where(matrix.index==user_id)[0][0]
        k =3   # number of top similar users who have rated the book
        # print(f"k = {k}")
        count =0
        # print(f"count = {count}")
        sum_sim_mul_rat = 0
        
        sum_sim = 0
        predicted_rate = 0
        similar_user_indices_with_similarity = get_similar_users(user_id, 0) # 0 in the parameter does not mean anything, not getting used
        
        
        book_index = np.where(matrix.columns==isbn)[0][0]
        
        for similar_user_index,similarity in similar_user_indices_with_similarity:
            # print(f"similar user index is {similar_user_index}")
            if(count==k):
                break
            else:
                if matrix.isnull().iloc[similar_user_index][book_index]:
                    continue
                if (matrix.iloc[similar_user_index][book_index]==0 or similarity==0):
                    continue
                
                count+=1
                sum_sim_mul_rat+= similarity*matrix.iloc[similar_user_index][book_index]
                sum_sim += similarity
                # print(f"rating of user_id {matrix.index[similar_user_index]} for book{book_index}: \"{matrix.columns[book_index]}\" is {matrix.iloc[similar_user_index][book_index]} \nsimilarity is {similarity} at count {count}")
        if sum_sim==0:
            return "Not possible to rate due to insufficient data"
        else:
            predicted_rate = sum_sim_mul_rat/sum_sim
            return predicted_rate
        
    else:
        return "User or Book not available for prediction"

In [329]:
get_rating_prediction(254, '0060392452')

8.291770598944957

In [330]:
get_rating_prediction(3, '0060392452')

'User or Book not available for prediction'

#### The next cell takes very long to execute

In [331]:
for user_id in matrix.index:
    print(get_rating_prediction(user_id, '0060392452'))

9.21681122464136
8.291770598944957
9.150359005446944
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.244236276887273
Not possible to rate due to insufficient data
8.05422322931216
7.514590967574722
Not possible to rate due to insufficient data
8.0
8.081335669925785
8.499228269089661
Not possible to rate due to insufficient data
7.271252843141348
9.388953654284386
8.0
Not possible to rate due to insufficient data
7.6605678087247275
9.680031272087176
8.0
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.541343266170996
9.635547308149107
6.577648793912232
8.98443425430401
Not possible to rate due to insufficient data
8.796691071345139
8.984747181781321
Not possible to rate due to insufficient data
7.2076928862023975
8.85754050538579
8.4236758168027
10.0
Not possible to rate due to insufficient data
7.456327173861108
Not possible to rate due to insufficient data
8.329450660014748
8.266336382202404
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.603193232760649
Not possible to rate due to insufficient data
7.503573502184054
7.946710898533231
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
5.371160012689372
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.128350301856421
6.879682946002875
8.505975047948807
9.029118601991012
Not possible to rate due to insufficient data
9.098829006765971
6.8554859374096075
8.0
8.79402596304992
Not possible to rate due to insufficient data
8.776491461660413
Not possible to rate due to insufficient data
8.751341762354404
Not possible to rate due to insufficient data
10.0
8.0
8.251174198788608
Not possible to rate due to insufficient data
8.889647957493118
9.67193135207466
Not possible to rate due to insufficient data
9.42612127118541
9.069594900298338
9.012771372189475
8.411689711118017
7.742649197034943
6.487785948140275
Not possible to rate due to insufficient data
8.5529202877488
7.898644218314471
7.022951755022075
9.999999999999998
8.0
7.585480723149375
9.819968419339475
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.063669230276842
Not possible to rate due to insufficient data
10.0
Not possible to rate due to insufficient data
8.0
3.714124754688587
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.509997382690976
7.772424525666838
8.458473262292197
6.756501280952185
7.113687328554273
9.28934503465393
8.570635199757476
7.300432211058504
7.973216040453814
8.36785934240145
8.384788607196784
6.914685192158281
Not possible to rate due to insufficient data
10.907075856206939
7.576323351038461
Not possible to rate due to insufficient data
8.263151952061902
19.45733412982458
13.37392047448355
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.5114879397453
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.71338976293049
8.248689794653565
9.190223570976121
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.681303702569185
7.608949999687761
Not possible to rate due to insufficient data
8.925196441124175
7.363013108887941
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.65069424364418
Not possible to rate due to insufficient data
7.359370886126814
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.221327403826841
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.26916103751825
8.55235104177066
Not possible to rate due to insufficient data
6.925289626868828
Not possible to rate due to insufficient data
7.767465112414987
8.625943642596667
11.038112298859186
5.401983226699754
Not possible to rate due to insufficient data
8.87964657844736
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.0
8.425611171843988
8.072212712211625
Not possible to rate due to insufficient data
3.671767460669872
8.02315601026008
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
6.488884960868318
6.9135734504226045
Not possible to rate due to insufficient data
8.585364025464377
8.250829050494165
7.259108317269382
10.378823457035757
9.173055559940975
7.935296012250262
10.077206754753792
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.718157297453661
8.534525931678939
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.227006983673602
Not possible to rate due to insufficient data
9.78177683285615
7.504780844799539
Not possible to rate due to insufficient data
9.348330670907757
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.540933428515347
9.356772526631403
8.147943077925765
8.497633932012391
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.858292581077908
8.197917143638785
9.006322487764173
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
10.0
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.965892168772848
7.387257969814849
Not possible to rate due to insufficient data
7.532948605497123
Not possible to rate due to insufficient data
9.790136836012065
8.506685076300899
Not possible to rate due to insufficient data
8.92171919560684
7.285532138755387
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.238664100498552
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
10.0
7.72389635300393
8.513846681193659
8.836944890553283
10.0
8.968416954952012
10.083164809462874
8.41069856613574
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.863544171057635
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.167947678655201
8.210633637278804
8.317916372343058
6.629903535592376
Not possible to rate due to insufficient data
7.75656109481461
4.017913076238282
9.226021022230325
8.687103345868213
Not possible to rate due to insufficient data
8.629379373063022
Not possible to rate due to insufficient data
8.7532150599593
8.27842428000004
Not possible to rate due to insufficient data
7.315259018203428
8.0
Not possible to rate due to insufficient data
9.716839857639583
8.0
10.0
Not possible to rate due to insufficient data
9.443147125534798
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.052228004550638
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
5.765786237341368
8.021484990338275
8.377886750979066
7.570741527160447
Not possible to rate due to insufficient data
8.268388021199248
6.649746087026418
8.965928219339375
3.296362888005243
Not possible to rate due to insufficient data
8.0
6.908681663162848
6.773336091394994
8.48762740493177
Not possible to rate due to insufficient data
8.16569531920773
9.680031272087176
8.93921648489352
8.742519858605869
6.857721035036707
7.483229726807178
Not possible to rate due to insufficient data
9.415423608246346
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.089470328400893
Not possible to rate due to insufficient data
9.089931304831671
8.034307585645175
6.945511850583239
9.70086463127741
7.371613287901507
8.986107742436253
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
6.621515229021992
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.878058281935104
8.301194301968733
7.979919805194547
9.18476351634682
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.609375582238425
7.426703961711854
8.948505350732807
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.162198252921356
Not possible to rate due to insufficient data
7.538573648006169
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.551460236655885
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.0
8.0
5.79710959858108
9.390973668862113
2.283247978460551
Not possible to rate due to insufficient data
6.358470440048915
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.0
9.331406006889157
Not possible to rate due to insufficient data
7.1851243027581955
8.00790991979199
8.4
8.855313338738632
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
6.935913929771013
8.257079748012565
10.954013313814478
8.350595603547053
Not possible to rate due to insufficient data
7.966182855306034
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.9739868683398125
8.0
Not possible to rate due to insufficient data
7.901372462200621
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
6.043055123725441
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.239282938434284
Not possible to rate due to insufficient data
9.899841804380568
Not possible to rate due to insufficient data
8.169280903901388
8.848786935141314
8.0
8.076102283849632
9.162210248181786
Not possible to rate due to insufficient data
7.815759191944355
8.434829674694651
9.937462452596383
8.44308290125485
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.302762399608902
Not possible to rate due to insufficient data
8.0
Not possible to rate due to insufficient data
8.066316130296613
7.917488140779368
8.359319404542362
8.385290133174836
7.194844558005775
Not possible to rate due to insufficient data
8.67633915174706
Not possible to rate due to insufficient data
7.404553727014727
8.130819218123047
Not possible to rate due to insufficient data
10.0
9.172105389026486
8.2270757410071
6.087106988142884
7.6050504120683815
Not possible to rate due to insufficient data
7.070050642891247
6.036412125877824
8.70961317057637
5.365490491333628
7.379763459588198
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.895876030120204
8.73396467472982
Not possible to rate due to insufficient data
7.811173855926212
8.245016550859653
7.42878825322477
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.070960337476045
Not possible to rate due to insufficient data
10.000000000000002
8.311304930355009
8.844683064204506
8.022074760086582
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.151865964714391
Not possible to rate due to insufficient data
8.886454911702634
Not possible to rate due to insufficient data
7.25399114102299
Not possible to rate due to insufficient data
2.951315241230438
7.268968953288461
8.867856621603291
Not possible to rate due to insufficient data
8.500743584536416
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.755568147413329
6.982955173629895
9.226268613782118
8.0
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.585814846295237
7.723896353003929
8.487627404931768
7.53735102244381
9.638558343708803
Not possible to rate due to insufficient data
7.863361575605445
Not possible to rate due to insufficient data
6.993420741436807
7.71493605338077
9.101209981531623
8.399987321856115
8.0
9.999999999999995
7.513912988219503
8.612693744207501
9.39349874722501
8.585031703093259
9.482763418593018
Not possible to rate due to insufficient data
6.821297452709247
9.316794283347386
Not possible to rate due to insufficient data
6.822083307386812
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
5.108708333995378
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.08875947683703
7.89011035640982
9.655007128823552
9.617165813570049
Not possible to rate due to insufficient data
7.834312333816537
Not possible to rate due to insufficient data
8.547141462231544
13.321637284273125
9.53071548896129
Not possible to rate due to insufficient data
7.646059306993006
Not possible to rate due to insufficient data
8.567354715895652
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.831796784330542
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
6.623158100225173
9.111992876244447
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.952975849041327
8.80946430672233
8.0
8.0
9.22852638760639
Not possible to rate due to insufficient data
8.644498593248061
8.664810013166157
Not possible to rate due to insufficient data
8.441139229597065
Not possible to rate due to insufficient data
8.50606102628815
Not possible to rate due to insufficient data
9.031898221780565
6.72717626620644
10.0
Not possible to rate due to insufficient data
8.34344549304465
8.299099841810385
8.729723530501227
8.770827777574874
7.26872111165509
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.999999999999998
8.248689794653565
9.570845512583961
8.48377448757858
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.834361643409283
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.144496428415325
10.0
6.913573450422606
8.157828864812421
9.156490519825176
Not possible to rate due to insufficient data
8.71135746548694
8.38099112150228
8.119843735408958
10.000000000000002
9.053460596793826
8.492983556021173
7.563123216714221
8.546797382612551
Not possible to rate due to insufficient data
7.578153113954265
8.436668744802397
Not possible to rate due to insufficient data
10.0
8.210948599884151
Not possible to rate due to insufficient data
8.35574257075105
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
6.913573450422605
7.787219651332475
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.513508620828329
Not possible to rate due to insufficient data
7.57632335103846
8.394398580437054
9.402063501664658
8.921533671889707
7.6674937498926745
Not possible to rate due to insufficient data
8.725962363672554
8.0
10.0
8.088503317036718
8.942974026419307
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.742715725552529
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.915946682547666
9.248636155543299
8.90370356416754
8.0
9.999999999999996
Not possible to rate due to insufficient data
7.86284806498233
8.77147558680679
6.664059652656645
6.857721035036706
8.83124316320609
7.475707822078392
Not possible to rate due to insufficient data
9.999999999999998
9.565726675791836
7.4499433168668014
8.267104406712843
7.336338819041261
8.0
Not possible to rate due to insufficient data
8.2270757410071
Not possible to rate due to insufficient data
5.059923892339197
7.763283277493472
8.783289557283661
7.449714537434316
8.0
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.7194786011845675
8.344171605303774
7.5652064644223085
7.327263184233908
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.859492818541045
8.349560838005548
Not possible to rate due to insufficient data
8.362281527081631
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.90095580199911
9.82295353059197
8.088503317036716
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.0
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.475049288195052
8.0
11.516285082569732
7.821253587747385
8.168023149062074
Not possible to rate due to insufficient data
9.63703666576513
12.332363588748281
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.0
3.3287307307570035
11.16350258948532
Not possible to rate due to insufficient data
8.434608425952174
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.630077329460933
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
7.797964127975922
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.402109038391444
7.223460015330086
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
8.616181865032674
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
9.33541904205873
Not possible to rate due to insufficient data
8.730414518383572
Not possible to rate due to insufficient data
8.635531426638842
Not possible to rate due to insufficient data
10.000000000000002
Not possible to rate due to insufficient data
7.995477686598907
7.10673505697612
6.9135734504226045
8.66091508200583
9.02567333741703
Not possible to rate due to insufficient data
7.9367063775222535
Not possible to rate due to insufficient data
8.168023149062074
7.076882663756392
Not possible to rate due to insufficient data
Not possible to rate due to insufficient data
10.000000000000002
Not possible to rate due to insufficient data
-1.2661562559890762
8.189949375065972
8.588290843821673
8.770317179031146
8.421555611318327
Not possible to rate due to insufficient data